
-- --------------------------------------------------
-- Entity Designer DDL Script for SQL Server 2005, 2008, 2012 and Azure
-- --------------------------------------------------
-- Date Created: 08/27/2019 09:17:57
-- Generated from EDMX file: D:\Proyect\RECEPTIO\Nucleo.Infraestructura\Modelo\ModeloReceptio.edmx
-- --------------------------------------------------

SET QUOTED_IDENTIFIER OFF;
GO
USE [RECEPTIO];
GO
IF SCHEMA_ID(N'dbo') IS NULL EXECUTE(N'CREATE SCHEMA [dbo]');
GO

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[FK__LINE_DEPO__ID_DE__4E1E9780]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[LINE_DEPOTS] DROP CONSTRAINT [FK__LINE_DEPO__ID_DE__4E1E9780];
GO
IF OBJECT_ID(N'[dbo].[FK__LINE_DEPO__ID_LI__4D2A7347]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[LINE_DEPOTS] DROP CONSTRAINT [FK__LINE_DEPO__ID_LI__4D2A7347];
GO
IF OBJECT_ID(N'[dbo].[FK__STOCK_REG__ID_DE__59904A2C]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[STOCK_REGISTER] DROP CONSTRAINT [FK__STOCK_REG__ID_DE__59904A2C];
GO
IF OBJECT_ID(N'[dbo].[FK__STOCK_REG__ID_LI__589C25F3]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[STOCK_REGISTER] DROP CONSTRAINT [FK__STOCK_REG__ID_LI__589C25F3];
GO
IF OBJECT_ID(N'[dbo].[FK__STOCK_REG__ID_OP__5A846E65]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[STOCK_REGISTER] DROP CONSTRAINT [FK__STOCK_REG__ID_OP__5A846E65];
GO
IF OBJECT_ID(N'[dbo].[FK_ACTIONPROCESS_TROUBLE_TICKET]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ACTIONS] DROP CONSTRAINT [FK_ACTIONPROCESS_TROUBLE_TICKET];
GO
IF OBJECT_ID(N'[dbo].[FK_AUTO_TROUBLE_REASONAUTO_TROUBLE_TICKET]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TROUBLE_TICKETS_AUTO_TROUBLE_TICKET] DROP CONSTRAINT [FK_AUTO_TROUBLE_REASONAUTO_TROUBLE_TICKET];
GO
IF OBJECT_ID(N'[dbo].[FK_AUTO_TROUBLE_TICKET_inherits_TROUBLE_TICKET]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TROUBLE_TICKETS_AUTO_TROUBLE_TICKET] DROP CONSTRAINT [FK_AUTO_TROUBLE_TICKET_inherits_TROUBLE_TICKET];
GO
IF OBJECT_ID(N'[dbo].[FK_AUTO_TROUBLE_TICKETUSER_SESSION]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TROUBLE_TICKETS_AUTO_TROUBLE_TICKET] DROP CONSTRAINT [FK_AUTO_TROUBLE_TICKETUSER_SESSION];
GO
IF OBJECT_ID(N'[dbo].[FK_BREAK_TYPEBREAK]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[BREAKS] DROP CONSTRAINT [FK_BREAK_TYPEBREAK];
GO
IF OBJECT_ID(N'[dbo].[FK_BY_PASSBY_PASS_AUDIT]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[BY_PASS_AUDITS] DROP CONSTRAINT [FK_BY_PASSBY_PASS_AUDIT];
GO
IF OBJECT_ID(N'[dbo].[FK_CLIENT_APP_TRANSACTION_TROUBLE_TICKET_inherits_TROUBLE_TICKET]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TROUBLE_TICKETS_CLIENT_APP_TRANSACTION_TROUBLE_TICKET] DROP CONSTRAINT [FK_CLIENT_APP_TRANSACTION_TROUBLE_TICKET_inherits_TROUBLE_TICKET];
GO
IF OBJECT_ID(N'[dbo].[FK_CONTAINERDAMAGE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[DAMAGES] DROP CONSTRAINT [FK_CONTAINERDAMAGE];
GO
IF OBJECT_ID(N'[dbo].[FK_CONTAINERSEAL]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[SEALS] DROP CONSTRAINT [FK_CONTAINERSEAL];
GO
IF OBJECT_ID(N'[dbo].[FK_DEVICEUSER_SESSION]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[USER_SESSIONS] DROP CONSTRAINT [FK_DEVICEUSER_SESSION];
GO
IF OBJECT_ID(N'[dbo].[FK_DEVICEZONE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[DEVICES] DROP CONSTRAINT [FK_DEVICEZONE];
GO
IF OBJECT_ID(N'[dbo].[FK_ERRORAPPLICATION]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ERRORS] DROP CONSTRAINT [FK_ERRORAPPLICATION];
GO
IF OBJECT_ID(N'[dbo].[FK_ERRORCLIENT_APP_TRANSACTION_TROUBLE_TICKET]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TROUBLE_TICKETS_CLIENT_APP_TRANSACTION_TROUBLE_TICKET] DROP CONSTRAINT [FK_ERRORCLIENT_APP_TRANSACTION_TROUBLE_TICKET];
GO
IF OBJECT_ID(N'[dbo].[FK_KIOSK_TRANSACTIONKIOSK]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[KIOSK_TRANSACTIONS] DROP CONSTRAINT [FK_KIOSK_TRANSACTIONKIOSK];
GO
IF OBJECT_ID(N'[dbo].[FK_KIOSK_TRANSACTIONPROCESS]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PROCESSES] DROP CONSTRAINT [FK_KIOSK_TRANSACTIONPROCESS];
GO
IF OBJECT_ID(N'[dbo].[FK_KIOSK_TRANSACTIONSENSOR_KIOSK_TRANSACTION]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[SENSOR_KIOSK_TRANSACTIONS] DROP CONSTRAINT [FK_KIOSK_TRANSACTIONSENSOR_KIOSK_TRANSACTION];
GO
IF OBJECT_ID(N'[dbo].[FK_KIOSKLIFT_UP_BARRIER]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[LIFT_UP_BARRIERS] DROP CONSTRAINT [FK_KIOSKLIFT_UP_BARRIER];
GO
IF OBJECT_ID(N'[dbo].[FK_KIOSKZONE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[KIOSKS] DROP CONSTRAINT [FK_KIOSKZONE];
GO
IF OBJECT_ID(N'[dbo].[FK_MOBILE_TROUBLE_TICKET_inherits_TROUBLE_TICKET]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TROUBLE_TICKETS_MOBILE_TROUBLE_TICKET] DROP CONSTRAINT [FK_MOBILE_TROUBLE_TICKET_inherits_TROUBLE_TICKET];
GO
IF OBJECT_ID(N'[dbo].[FK_MOBILE_TROUBLE_TICKETTOS_PROCCESS]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TOS_PROCCESSES] DROP CONSTRAINT [FK_MOBILE_TROUBLE_TICKETTOS_PROCCESS];
GO
IF OBJECT_ID(N'[dbo].[FK_MOBILE_TROUBLE_TICKETZONE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TROUBLE_TICKETS_MOBILE_TROUBLE_TICKET] DROP CONSTRAINT [FK_MOBILE_TROUBLE_TICKETZONE];
GO
IF OBJECT_ID(N'[dbo].[FK_MOTIVESUB_MOTIVE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[SUB_MOTIVES] DROP CONSTRAINT [FK_MOTIVESUB_MOTIVE];
GO
IF OBJECT_ID(N'[dbo].[FK_PRE_GATE_DETAILCONTAINER]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CONTAINERS] DROP CONSTRAINT [FK_PRE_GATE_DETAILCONTAINER];
GO
IF OBJECT_ID(N'[dbo].[FK_PRE_GATEBY_PASS]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[BY_PASSES] DROP CONSTRAINT [FK_PRE_GATEBY_PASS];
GO
IF OBJECT_ID(N'[dbo].[FK_PRE_GATEDEVICE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PRE_GATES] DROP CONSTRAINT [FK_PRE_GATEDEVICE];
GO
IF OBJECT_ID(N'[dbo].[FK_PRE_GATEKIOSK_TRANSACTION]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[KIOSK_TRANSACTIONS] DROP CONSTRAINT [FK_PRE_GATEKIOSK_TRANSACTION];
GO
IF OBJECT_ID(N'[dbo].[FK_PRE_GATEPRE_GATE_DETAIL]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PRE_GATE_DETAILS] DROP CONSTRAINT [FK_PRE_GATEPRE_GATE_DETAIL];
GO
IF OBJECT_ID(N'[dbo].[FK_PRE_GATETROUBLE_TICKETS_MOBILE_TROUBLE_TICKET]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TROUBLE_TICKETS_MOBILE_TROUBLE_TICKET] DROP CONSTRAINT [FK_PRE_GATETROUBLE_TICKETS_MOBILE_TROUBLE_TICKET];
GO
IF OBJECT_ID(N'[dbo].[FK_PROCESS_TROUBLE_TICKET_inherits_TROUBLE_TICKET]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TROUBLE_TICKETS_PROCESS_TROUBLE_TICKET] DROP CONSTRAINT [FK_PROCESS_TROUBLE_TICKET_inherits_TROUBLE_TICKET];
GO
IF OBJECT_ID(N'[dbo].[FK_PROCESS_TROUBLE_TICKETREASSIGNMENT]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[REASSIGNMENTS] DROP CONSTRAINT [FK_PROCESS_TROUBLE_TICKETREASSIGNMENT];
GO
IF OBJECT_ID(N'[dbo].[FK_PROCESSMESSAGE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PROCESSES] DROP CONSTRAINT [FK_PROCESSMESSAGE];
GO
IF OBJECT_ID(N'[dbo].[FK_PROCESSPROCESS_TROUBLE_TICKET]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TROUBLE_TICKETS_PROCESS_TROUBLE_TICKET] DROP CONSTRAINT [FK_PROCESSPROCESS_TROUBLE_TICKET];
GO
IF OBJECT_ID(N'[dbo].[FK_REASSIGNMENTREASSIGNMENT_MOTIVE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[REASSIGNMENTS] DROP CONSTRAINT [FK_REASSIGNMENTREASSIGNMENT_MOTIVE];
GO
IF OBJECT_ID(N'[dbo].[FK_REASSIGNMENTUSER_SESSION]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[REASSIGNMENTS] DROP CONSTRAINT [FK_REASSIGNMENTUSER_SESSION];
GO
IF OBJECT_ID(N'[dbo].[FK_REPRINTKIOSK]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[REPRINTS] DROP CONSTRAINT [FK_REPRINTKIOSK];
GO
IF OBJECT_ID(N'[dbo].[FK_REPRINTPRE_GATE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[REPRINTS] DROP CONSTRAINT [FK_REPRINTPRE_GATE];
GO
IF OBJECT_ID(N'[dbo].[FK_REPRINTTROUBLE_DESK_USER]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[REPRINTS] DROP CONSTRAINT [FK_REPRINTTROUBLE_DESK_USER];
GO
IF OBJECT_ID(N'[dbo].[FK_SENSORSENSOR_KIOSK_TRANSACTION]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[SENSOR_KIOSK_TRANSACTIONS] DROP CONSTRAINT [FK_SENSORSENSOR_KIOSK_TRANSACTION];
GO
IF OBJECT_ID(N'[dbo].[FK_TOS_PROCCESSPRE_GATE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TOS_PROCCESSES] DROP CONSTRAINT [FK_TOS_PROCCESSPRE_GATE];
GO
IF OBJECT_ID(N'[dbo].[FK_TRANSACTION_TYPEPRE_GATE_DETAIL]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PRE_GATE_DETAILS] DROP CONSTRAINT [FK_TRANSACTION_TYPEPRE_GATE_DETAIL];
GO
IF OBJECT_ID(N'[dbo].[FK_TROUBLE_DESK_USERBY_PASS_AUDIT]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[BY_PASS_AUDITS] DROP CONSTRAINT [FK_TROUBLE_DESK_USERBY_PASS_AUDIT];
GO
IF OBJECT_ID(N'[dbo].[FK_TROUBLE_DESK_USERLIFT_UP_BARRIER]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[LIFT_UP_BARRIERS] DROP CONSTRAINT [FK_TROUBLE_DESK_USERLIFT_UP_BARRIER];
GO
IF OBJECT_ID(N'[dbo].[FK_TROUBLE_DESK_USERUSER_SESSION]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[USER_SESSIONS] DROP CONSTRAINT [FK_TROUBLE_DESK_USERUSER_SESSION];
GO
IF OBJECT_ID(N'[dbo].[FK_TYPE_ERRORERROR]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ERRORS] DROP CONSTRAINT [FK_TYPE_ERRORERROR];
GO
IF OBJECT_ID(N'[dbo].[FK_USER_SESSIONBREAK]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[BREAKS] DROP CONSTRAINT [FK_USER_SESSIONBREAK];
GO
IF OBJECT_ID(N'[dbo].[FK_USER_SESSIONCLIENT_APP_TRANSACTION_TROUBLE_TICKET]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TROUBLE_TICKETS_CLIENT_APP_TRANSACTION_TROUBLE_TICKET] DROP CONSTRAINT [FK_USER_SESSIONCLIENT_APP_TRANSACTION_TROUBLE_TICKET];
GO
IF OBJECT_ID(N'[dbo].[FK_USER_SESSIONMOBILE_TROUBLE_TICKET]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TROUBLE_TICKETS_MOBILE_TROUBLE_TICKET] DROP CONSTRAINT [FK_USER_SESSIONMOBILE_TROUBLE_TICKET];
GO
IF OBJECT_ID(N'[dbo].[FK_USER_SESSIONPROCESS_TROUBLE_TICKET]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TROUBLE_TICKETS_PROCESS_TROUBLE_TICKET] DROP CONSTRAINT [FK_USER_SESSIONPROCESS_TROUBLE_TICKET];
GO
IF OBJECT_ID(N'[dbo].[FK_ZONECLIENT_APP_TRANSACTION_TROUBLE_TICKET]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TROUBLE_TICKETS_CLIENT_APP_TRANSACTION_TROUBLE_TICKET] DROP CONSTRAINT [FK_ZONECLIENT_APP_TRANSACTION_TROUBLE_TICKET];
GO
IF OBJECT_ID(N'[dbo].[FK_ZONETRANSACTION_TYPE_TRANSACTION_TYPE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ZONETRANSACTION_TYPE] DROP CONSTRAINT [FK_ZONETRANSACTION_TYPE_TRANSACTION_TYPE];
GO
IF OBJECT_ID(N'[dbo].[FK_ZONETRANSACTION_TYPE_ZONE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ZONETRANSACTION_TYPE] DROP CONSTRAINT [FK_ZONETRANSACTION_TYPE_ZONE];
GO
IF OBJECT_ID(N'[dbo].[FK_STOCK_PREGATE_COST]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[STOCK_REGISTER] DROP CONSTRAINT [FK_STOCK_PREGATE_COST];
GO

-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[ACTIONS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[ACTIONS];
GO
IF OBJECT_ID(N'[dbo].[APPLICATIONS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[APPLICATIONS];
GO
IF OBJECT_ID(N'[dbo].[AUTO_TROUBLE_REASONS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[AUTO_TROUBLE_REASONS];
GO
IF OBJECT_ID(N'[dbo].[BREAK_TYPES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[BREAK_TYPES];
GO
IF OBJECT_ID(N'[dbo].[BREAKS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[BREAKS];
GO
IF OBJECT_ID(N'[dbo].[BY_PASS_AUDITS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[BY_PASS_AUDITS];
GO
IF OBJECT_ID(N'[dbo].[BY_PASSES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[BY_PASSES];
GO
IF OBJECT_ID(N'[dbo].[CONTAINERS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CONTAINERS];
GO
IF OBJECT_ID(N'[dbo].[DAMAGES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[DAMAGES];
GO
IF OBJECT_ID(N'[dbo].[DEPOT]', 'U') IS NOT NULL
    DROP TABLE [dbo].[DEPOT];
GO
IF OBJECT_ID(N'[dbo].[DEVICES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[DEVICES];
GO
IF OBJECT_ID(N'[dbo].[ERRORS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[ERRORS];
GO
IF OBJECT_ID(N'[dbo].[KIOSK_TRANSACTIONS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[KIOSK_TRANSACTIONS];
GO
IF OBJECT_ID(N'[dbo].[KIOSKS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[KIOSKS];
GO
IF OBJECT_ID(N'[dbo].[LIFT_UP_BARRIERS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[LIFT_UP_BARRIERS];
GO
IF OBJECT_ID(N'[dbo].[LINE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[LINE];
GO
IF OBJECT_ID(N'[dbo].[LINE_DEPOTS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[LINE_DEPOTS];
GO
IF OBJECT_ID(N'[dbo].[MESSAGES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[MESSAGES];
GO
IF OBJECT_ID(N'[dbo].[MOTIVES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[MOTIVES];
GO
IF OBJECT_ID(N'[dbo].[PRE_GATE_DETAILS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PRE_GATE_DETAILS];
GO
IF OBJECT_ID(N'[dbo].[PRE_GATES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PRE_GATES];
GO
IF OBJECT_ID(N'[dbo].[PROCESSES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PROCESSES];
GO
IF OBJECT_ID(N'[dbo].[REASSIGNMENT_MOTIVES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[REASSIGNMENT_MOTIVES];
GO
IF OBJECT_ID(N'[dbo].[REASSIGNMENTS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[REASSIGNMENTS];
GO
IF OBJECT_ID(N'[dbo].[REPRINTS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[REPRINTS];
GO
IF OBJECT_ID(N'[dbo].[SEALS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[SEALS];
GO
IF OBJECT_ID(N'[dbo].[SENSOR_KIOSK_TRANSACTIONS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[SENSOR_KIOSK_TRANSACTIONS];
GO
IF OBJECT_ID(N'[dbo].[SENSORS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[SENSORS];
GO
IF OBJECT_ID(N'[dbo].[STOCK_OPERATION]', 'U') IS NOT NULL
    DROP TABLE [dbo].[STOCK_OPERATION];
GO
IF OBJECT_ID(N'[dbo].[STOCK_REGISTER]', 'U') IS NOT NULL
    DROP TABLE [dbo].[STOCK_REGISTER];
GO
IF OBJECT_ID(N'[dbo].[SUB_MOTIVES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[SUB_MOTIVES];
GO
IF OBJECT_ID(N'[dbo].[TOS_PROCCESSES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TOS_PROCCESSES];
GO
IF OBJECT_ID(N'[dbo].[TRANSACTION_TYPES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TRANSACTION_TYPES];
GO
IF OBJECT_ID(N'[dbo].[TROUBLE_DESK_USERS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TROUBLE_DESK_USERS];
GO
IF OBJECT_ID(N'[dbo].[TROUBLE_TICKETS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TROUBLE_TICKETS];
GO
IF OBJECT_ID(N'[dbo].[TROUBLE_TICKETS_AUTO_TROUBLE_TICKET]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TROUBLE_TICKETS_AUTO_TROUBLE_TICKET];
GO
IF OBJECT_ID(N'[dbo].[TROUBLE_TICKETS_CLIENT_APP_TRANSACTION_TROUBLE_TICKET]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TROUBLE_TICKETS_CLIENT_APP_TRANSACTION_TROUBLE_TICKET];
GO
IF OBJECT_ID(N'[dbo].[TROUBLE_TICKETS_MOBILE_TROUBLE_TICKET]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TROUBLE_TICKETS_MOBILE_TROUBLE_TICKET];
GO
IF OBJECT_ID(N'[dbo].[TROUBLE_TICKETS_PROCESS_TROUBLE_TICKET]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TROUBLE_TICKETS_PROCESS_TROUBLE_TICKET];
GO
IF OBJECT_ID(N'[dbo].[TYPE_ERRORS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TYPE_ERRORS];
GO
IF OBJECT_ID(N'[dbo].[USER_SESSIONS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[USER_SESSIONS];
GO
IF OBJECT_ID(N'[dbo].[ZONES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[ZONES];
GO
IF OBJECT_ID(N'[dbo].[ZONETRANSACTION_TYPE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[ZONETRANSACTION_TYPE];
GO

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'PRE_GATES'
CREATE TABLE [dbo].[PRE_GATES] (
    [PRE_GATE_ID] bigint  NOT NULL,
    [CREATION_DATE] datetime  NOT NULL,
    [USER] nvarchar(20)  NOT NULL,
    [DRIVER_ID] nvarchar(15)  NOT NULL,
    [TRUCK_LICENCE] nvarchar(10)  NOT NULL,
    [IS_RECYCLED] bit  NOT NULL,
    [DEVICE_ID] int  NOT NULL,
    [STATUS] nvarchar(1)  NOT NULL,
    [CONCURRENCY] binary(8)  NOT NULL,
    [PRE_GATE_ID_REF] bigint  NULL
);
GO

-- Creating table 'CONTAINERS'
CREATE TABLE [dbo].[CONTAINERS] (
    [CONTAINER_ID] int IDENTITY(1,1) NOT NULL,
    [NUMBER] nvarchar(30)  NOT NULL,
    [IS_RECYCLED] bit  NOT NULL,
    [PRE_GATE_DETAIL_ID] bigint  NOT NULL
);
GO

-- Creating table 'SEALS'
CREATE TABLE [dbo].[SEALS] (
    [SEAL_ID] int IDENTITY(1,1) NOT NULL,
    [CAPTION] nvarchar(20)  NOT NULL,
    [VALUE] nvarchar(20)  NOT NULL,
    [CONTAINER_ID] int  NOT NULL,
    [IS_RECYCLED] bit  NOT NULL
);
GO

-- Creating table 'KIOSK_TRANSACTIONS'
CREATE TABLE [dbo].[KIOSK_TRANSACTIONS] (
    [TRANSACTION_ID] int IDENTITY(1,1) NOT NULL,
    [IS_OK] bit  NOT NULL,
    [START_DATE] datetime  NOT NULL,
    [END_DATE] datetime  NOT NULL,
    [IS_RECYCLED] bit  NOT NULL,
    [KIOSK_ID] smallint  NOT NULL,
    [PRE_GATE_ID] bigint  NULL
);
GO

-- Creating table 'PROCESSES'
CREATE TABLE [dbo].[PROCESSES] (
    [PROCESS_ID] bigint IDENTITY(1,1) NOT NULL,
    [STEP] nvarchar(20)  NOT NULL,
    [STEP_DATE] datetime  NOT NULL,
    [IS_OK] bit  NOT NULL,
    [RESPONSE] nvarchar(max)  NOT NULL,
    [IS_RECYCLED] bit  NOT NULL,
    [TRANSACTION_ID] int  NOT NULL,
    [MESSAGE_ID] int  NOT NULL
);
GO

-- Creating table 'ZONES'
CREATE TABLE [dbo].[ZONES] (
    [ZONE_ID] smallint IDENTITY(1,1) NOT NULL,
    [NAME] nvarchar(30)  NOT NULL,
    [IS_ACTIVE] bit  NOT NULL
);
GO

-- Creating table 'KIOSKS'
CREATE TABLE [dbo].[KIOSKS] (
    [KIOSK_ID] smallint IDENTITY(1,1) NOT NULL,
    [NAME] nvarchar(30)  NOT NULL,
    [IP] nvarchar(75)  NOT NULL,
    [IS_ACTIVE] bit  NOT NULL,
    [ZONE_ID] smallint  NOT NULL,
    [IS_IN] bit  NOT NULL
);
GO

-- Creating table 'TROUBLE_TICKETS'
CREATE TABLE [dbo].[TROUBLE_TICKETS] (
    [TT_ID] bigint IDENTITY(1,1) NOT NULL,
    [CREATION_DATE] datetime  NOT NULL,
    [ACCEPTANCE_DATE] datetime  NULL,
    [FINISH_DATE] datetime  NULL,
    [NOTES] nvarchar(max)  NULL,
    [IS_CANCEL] bit  NOT NULL,
    [IS_RECYCLED] bit  NOT NULL,
    [ASSIGNMENT_DATE] datetime  NULL,
    [CANCEL_USER] nvarchar(20)  NULL,
    [CANCEL_DATE] datetime  NULL,
    [SUBMOTIVE_ID] int  NULL,
    [MOTIVE_ID] int  NULL
);
GO

-- Creating table 'TROUBLE_DESK_USERS'
CREATE TABLE [dbo].[TROUBLE_DESK_USERS] (
    [TTU_ID] int IDENTITY(1,1) NOT NULL,
    [FIRST_NAME] nvarchar(100)  NOT NULL,
    [LAST_NAME] nvarchar(100)  NOT NULL,
    [USER_NAME] nvarchar(30)  NOT NULL,
    [IS_ACTIVE] bit  NOT NULL,
    [EMAIL] nvarchar(50)  NOT NULL,
    [IS_TD] bit  NOT NULL,
    [IS_SUPERVISOR] bit  NOT NULL
);
GO

-- Creating table 'DEVICES'
CREATE TABLE [dbo].[DEVICES] (
    [DEVICE_ID] int IDENTITY(1,1) NOT NULL,
    [IP] nvarchar(75)  NOT NULL,
    [NAME] nvarchar(30)  NOT NULL,
    [IS_ACTIVE] bit  NOT NULL,
    [ZONE_ID] smallint  NOT NULL
);
GO

-- Creating table 'USER_SESSIONS'
CREATE TABLE [dbo].[USER_SESSIONS] (
    [ID] bigint IDENTITY(1,1) NOT NULL,
    [START_SESSION__DATE] datetime  NOT NULL,
    [FINISH_SESSION_DATE] datetime  NULL,
    [DEVICE_ID] int  NOT NULL,
    [TTU_ID] int  NOT NULL,
    [IS_RECYCLED] bit  NOT NULL
);
GO

-- Creating table 'BREAKS'
CREATE TABLE [dbo].[BREAKS] (
    [BREAK_ID] int IDENTITY(1,1) NOT NULL,
    [START_BREAK_DATE] datetime  NOT NULL,
    [FINISH_BREAK_DATE] datetime  NULL,
    [BREAK_TYPE_ID] tinyint  NOT NULL,
    [USER_SESSION_ID] bigint  NOT NULL,
    [IS_RECYCLED] bit  NOT NULL
);
GO

-- Creating table 'BREAK_TYPES'
CREATE TABLE [dbo].[BREAK_TYPES] (
    [ID] tinyint IDENTITY(1,1) NOT NULL,
    [NAME] nvarchar(50)  NOT NULL,
    [IS_ACTIVE] bit  NOT NULL
);
GO

-- Creating table 'REASSIGNMENTS'
CREATE TABLE [dbo].[REASSIGNMENTS] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [DATE] datetime  NOT NULL,
    [USER_SESSION_ID] bigint  NOT NULL,
    [IS_RECYCLED] bit  NOT NULL,
    [USER] nvarchar(30)  NOT NULL,
    [MOTIVE_ID] int  NOT NULL,
    [TT_ID] bigint  NOT NULL
);
GO

-- Creating table 'MESSAGES'
CREATE TABLE [dbo].[MESSAGES] (
    [MESSAGE_ID] int IDENTITY(1,1) NOT NULL,
    [USER_MESSAGE] nvarchar(512)  NOT NULL,
    [TROUBLE_DESK_MESSAGE] nvarchar(max)  NOT NULL,
    [DETAILS] nvarchar(max)  NOT NULL,
    [TYPE] nvarchar(1)  NOT NULL,
    [ATTEMPTS] tinyint  NOT NULL
);
GO

-- Creating table 'REASSIGNMENT_MOTIVES'
CREATE TABLE [dbo].[REASSIGNMENT_MOTIVES] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [CAPTION] nvarchar(30)  NOT NULL,
    [IS_ACTIVE] bit  NOT NULL
);
GO

-- Creating table 'AUTO_TROUBLE_REASONS'
CREATE TABLE [dbo].[AUTO_TROUBLE_REASONS] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [CAPTION] nvarchar(30)  NOT NULL,
    [IS_ACTIVE] bit  NOT NULL
);
GO

-- Creating table 'ERRORS'
CREATE TABLE [dbo].[ERRORS] (
    [ERROR_ID] int IDENTITY(1,1) NOT NULL,
    [THROW_ON] datetime  NOT NULL,
    [MESSAGE] nvarchar(max)  NOT NULL,
    [DETAILS] nvarchar(max)  NOT NULL,
    [APPLICATION_ID] int  NOT NULL,
    [TYPE_ERROR_ID] int  NOT NULL,
    [IP_SOURCE] nvarchar(75)  NULL
);
GO

-- Creating table 'APPLICATIONS'
CREATE TABLE [dbo].[APPLICATIONS] (
    [APPLICATION_ID] int IDENTITY(1,1) NOT NULL,
    [NAME] nvarchar(30)  NOT NULL,
    [IS_ACTIVE] bit  NOT NULL,
    [VERSION] nvarchar(15)  NOT NULL,
    [PATH] nvarchar(max)  NOT NULL
);
GO

-- Creating table 'TYPE_ERRORS'
CREATE TABLE [dbo].[TYPE_ERRORS] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [NAME] nvarchar(20)  NOT NULL
);
GO

-- Creating table 'PRE_GATE_DETAILS'
CREATE TABLE [dbo].[PRE_GATE_DETAILS] (
    [ID] bigint IDENTITY(1,1) NOT NULL,
    [TRANSACTION_NUMBER] nvarchar(50)  NOT NULL,
    [IS_RECYCLED] bit  NOT NULL,
    [TRANSACTION_TYPE_ID] smallint  NOT NULL,
    [PRE_GATE_ID] bigint  NOT NULL,
    [STATUS] nchar(1)  NULL,
    [DOCUMENT_ID] varchar(100)  NULL,
    [REFERENCE_ID] varchar(500)  NULL
);
GO

-- Creating table 'DAMAGES'
CREATE TABLE [dbo].[DAMAGES] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [DAMAGE_TYPE] nvarchar(15)  NOT NULL,
    [COMPONENT] nvarchar(20)  NOT NULL,
    [SEVERITY] nvarchar(30)  NOT NULL,
    [LOCATION] nvarchar(255)  NOT NULL,
    [QUANTITY] smallint  NOT NULL,
    [NOTES] nvarchar(max)  NOT NULL,
    [CONTAINER_ID] int  NOT NULL
);
GO

-- Creating table 'TRANSACTION_TYPES'
CREATE TABLE [dbo].[TRANSACTION_TYPES] (
    [ID] smallint IDENTITY(1,1) NOT NULL,
    [CODE] nvarchar(7)  NOT NULL,
    [DESCRIPTION] nvarchar(255)  NOT NULL
);
GO

-- Creating table 'ACTIONS'
CREATE TABLE [dbo].[ACTIONS] (
    [ACTION_ID] int IDENTITY(1,1) NOT NULL,
    [ACTION_NAME] nvarchar(20)  NOT NULL,
    [ACTION_DATE] datetime  NOT NULL,
    [TT_ID] bigint  NOT NULL
);
GO

-- Creating table 'TOS_PROCCESSES'
CREATE TABLE [dbo].[TOS_PROCCESSES] (
    [ID] bigint IDENTITY(1,1) NOT NULL,
    [STEP] nvarchar(20)  NOT NULL,
    [STEP_DATE] datetime  NOT NULL,
    [IS_OK] bit  NOT NULL,
    [RESPONSE] nvarchar(max)  NOT NULL,
    [IS_RECYCLED] bit  NOT NULL,
    [PRE_GATE_ID] bigint  NOT NULL,
    [MOBILE_TROUBLE_TICKET_TT_ID] bigint  NULL
);
GO

-- Creating table 'SENSORS'
CREATE TABLE [dbo].[SENSORS] (
    [SENSOR_ID] smallint IDENTITY(1,1) NOT NULL,
    [NAME] nvarchar(100)  NOT NULL
);
GO

-- Creating table 'SENSOR_KIOSK_TRANSACTIONS'
CREATE TABLE [dbo].[SENSOR_KIOSK_TRANSACTIONS] (
    [ID] bigint IDENTITY(1,1) NOT NULL,
    [VALUE] bit  NOT NULL,
    [SENSOR_ID] smallint  NOT NULL,
    [TRANSACTION_ID] int  NOT NULL
);
GO

-- Creating table 'LIFT_UP_BARRIERS'
CREATE TABLE [dbo].[LIFT_UP_BARRIERS] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [DATE] datetime  NOT NULL,
    [REASON] nvarchar(max)  NOT NULL,
    [KIOSK_ID] smallint  NOT NULL,
    [TTU_ID] int  NOT NULL,
    [PREGATE_ID] bigint  NULL,
    [MOTIVE_ID] int  NULL
);
GO

-- Creating table 'REPRINTS'
CREATE TABLE [dbo].[REPRINTS] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [DATE] datetime  NOT NULL,
    [TTU_ID] int  NOT NULL,
    [PRE_GATE_ID] bigint  NOT NULL,
    [KIOSK_ID] smallint  NOT NULL
);
GO

-- Creating table 'BY_PASSES'
CREATE TABLE [dbo].[BY_PASSES] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [REASON] nvarchar(max)  NOT NULL,
    [IS_ENABLED] bit  NOT NULL,
    [PRE_GATE_PRE_GATE_ID] bigint  NOT NULL
);
GO

-- Creating table 'BY_PASS_AUDITS'
CREATE TABLE [dbo].[BY_PASS_AUDITS] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [DATE] datetime  NOT NULL,
    [FIELD] nvarchar(50)  NOT NULL,
    [OLD_VALUE] nvarchar(max)  NOT NULL,
    [NEW_VALUE] nvarchar(max)  NOT NULL,
    [TTU_ID] int  NOT NULL,
    [BY_PASS_ID] int  NOT NULL
);
GO

-- Creating table 'DEPOT'
CREATE TABLE [dbo].[DEPOT] (
    [ID_DEPOT] int IDENTITY(1,1) NOT NULL,
    [NAME] nvarchar(250)  NOT NULL,
    [NOTES] varchar(max)  NULL,
    [ACTIVE] bit  NULL,
    [AUXILIAR_STOCK] int  NULL,
    [CREATE_DATE] datetime  NULL
);
GO

-- Creating table 'LINE'
CREATE TABLE [dbo].[LINE] (
    [ID] nvarchar(5)  NOT NULL,
    [NAME] nvarchar(250)  NULL,
    [MAIL_STOCK] nvarchar(100)  NULL,
    [STOCK] int  NULL,
    [NOTES] varchar(max)  NULL,
    [ACTIVE] bit  NULL,
    [CREATE_DATE] datetime  NULL,
    [ID_LINE] int IDENTITY(1,1) NOT NULL
);
GO

-- Creating table 'LINE_DEPOTS'
CREATE TABLE [dbo].[LINE_DEPOTS] (
    [ID_LINE_DEPO] bigint IDENTITY(1,1) NOT NULL,
    [ID_LINE] int  NOT NULL,
    [ID_DEPOT] int  NOT NULL,
    [ACTIVE] bit  NOT NULL,
    [CREATE_USER] varchar(50)  NOT NULL,
    [CREATE_DATE] datetime  NULL,
    [MOD_DATE] datetime  NULL,
    [MOD_USER] varchar(50)  NULL
);
GO

-- Creating table 'STOCK_OPERATION'
CREATE TABLE [dbo].[STOCK_OPERATION] (
    [ID_OPERATION] int IDENTITY(1,1) NOT NULL,
    [OPERATION] nvarchar(25)  NOT NULL,
    [MULTIPLIER] int  NULL,
    [NOTES] varchar(max)  NULL,
    [ACTIVE] bit  NOT NULL,
    [CREATE_USER] varchar(50)  NOT NULL,
    [CREATE_DATE] datetime  NULL,
    [MOD_DATE] datetime  NULL,
    [MOD_USER] varchar(50)  NULL,
    [SCREEN] bit  NULL
);
GO

-- Creating table 'STOCK_REGISTER'
CREATE TABLE [dbo].[STOCK_REGISTER] (
    [ID_LINE] int  NOT NULL,
    [ID_DEPOT] int  NOT NULL,
    [ID_OPERATION] int  NOT NULL,
    [PRE_GATE_ID] bigint  NULL,
    [PRE_GATE_DETAILS_ID] bigint  NULL,
    [OPERATION_USER] nvarchar(50)  NOT NULL,
    [OPERATION_OBJETC] nvarchar(50)  NOT NULL,
    [OPERATION_NOTES] varchar(500)  NULL,
    [QTY] int  NOT NULL,
    [MULTIPLIER] int  NOT NULL,
    [ACTIVE] bit  NULL,
    [CREATE_DATE] datetime  NULL,
    [CREATE_YEAR] int  NULL,
    [CREATE_MONTH] int  NULL,
    [CREATE_WEEK] int  NULL,
    [ID] bigint IDENTITY(1,1) NOT NULL,
    [REGISTER_DATE] datetime  NULL
);
GO

-- Creating table 'MOTIVES'
CREATE TABLE [dbo].[MOTIVES] (
    [MOTIVE_ID] int IDENTITY(1,1) NOT NULL,
    [NAME] varchar(100)  NOT NULL,
    [ACTIVE] bit  NOT NULL,
    [TYPE] smallint  NOT NULL
);
GO

-- Creating table 'SUB_MOTIVES'
CREATE TABLE [dbo].[SUB_MOTIVES] (
    [SUB_MOTIVE_ID] int IDENTITY(1,1) NOT NULL,
    [NAME] nvarchar(max)  NOT NULL,
    [ACTIVE] bit  NOT NULL,
    [MOTIVES_ID] int  NOT NULL
);
GO

-- Creating table 'TROUBLE_TICKETS_AUTO_TROUBLE_TICKET'
CREATE TABLE [dbo].[TROUBLE_TICKETS_AUTO_TROUBLE_TICKET] (
    [REASON_ID] int  NOT NULL,
    [USER_SESSION_ID] bigint  NOT NULL,
    [TT_ID] bigint  NOT NULL
);
GO

-- Creating table 'TROUBLE_TICKETS_PROCESS_TROUBLE_TICKET'
CREATE TABLE [dbo].[TROUBLE_TICKETS_PROCESS_TROUBLE_TICKET] (
    [USER_SESSION_ID] bigint  NULL,
    [IS_SUSPENDED] bit  NOT NULL,
    [TT_ID] bigint  NOT NULL,
    [PROCESS_PROCESS_ID] bigint  NOT NULL
);
GO

-- Creating table 'TROUBLE_TICKETS_MOBILE_TROUBLE_TICKET'
CREATE TABLE [dbo].[TROUBLE_TICKETS_MOBILE_TROUBLE_TICKET] (
    [USER_SESSION_ID] bigint  NULL,
    [MESSAGE] nvarchar(max)  NOT NULL,
    [ZONE_ID] smallint  NOT NULL,
    [PRE_GATE_ID] bigint  NULL,
    [TT_ID] bigint  NOT NULL
);
GO

-- Creating table 'TROUBLE_TICKETS_CLIENT_APP_TRANSACTION_TROUBLE_TICKET'
CREATE TABLE [dbo].[TROUBLE_TICKETS_CLIENT_APP_TRANSACTION_TROUBLE_TICKET] (
    [USER_SESSION_ID] bigint  NULL,
    [ZONE_ID] smallint  NOT NULL,
    [TT_ID] bigint  NOT NULL,
    [ERROR_ERROR_ID] int  NOT NULL
);
GO

-- Creating table 'ZONETRANSACTION_TYPE'
CREATE TABLE [dbo].[ZONETRANSACTION_TYPE] (
    [ZONES_ZONE_ID] smallint  NOT NULL,
    [TRANSACTION_TYPES_ID] smallint  NOT NULL
);
GO

-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on [PRE_GATE_ID] in table 'PRE_GATES'
ALTER TABLE [dbo].[PRE_GATES]
ADD CONSTRAINT [PK_PRE_GATES]
    PRIMARY KEY CLUSTERED ([PRE_GATE_ID] ASC);
GO

-- Creating primary key on [CONTAINER_ID] in table 'CONTAINERS'
ALTER TABLE [dbo].[CONTAINERS]
ADD CONSTRAINT [PK_CONTAINERS]
    PRIMARY KEY CLUSTERED ([CONTAINER_ID] ASC);
GO

-- Creating primary key on [SEAL_ID] in table 'SEALS'
ALTER TABLE [dbo].[SEALS]
ADD CONSTRAINT [PK_SEALS]
    PRIMARY KEY CLUSTERED ([SEAL_ID] ASC);
GO

-- Creating primary key on [TRANSACTION_ID] in table 'KIOSK_TRANSACTIONS'
ALTER TABLE [dbo].[KIOSK_TRANSACTIONS]
ADD CONSTRAINT [PK_KIOSK_TRANSACTIONS]
    PRIMARY KEY CLUSTERED ([TRANSACTION_ID] ASC);
GO

-- Creating primary key on [PROCESS_ID] in table 'PROCESSES'
ALTER TABLE [dbo].[PROCESSES]
ADD CONSTRAINT [PK_PROCESSES]
    PRIMARY KEY CLUSTERED ([PROCESS_ID] ASC);
GO

-- Creating primary key on [ZONE_ID] in table 'ZONES'
ALTER TABLE [dbo].[ZONES]
ADD CONSTRAINT [PK_ZONES]
    PRIMARY KEY CLUSTERED ([ZONE_ID] ASC);
GO

-- Creating primary key on [KIOSK_ID] in table 'KIOSKS'
ALTER TABLE [dbo].[KIOSKS]
ADD CONSTRAINT [PK_KIOSKS]
    PRIMARY KEY CLUSTERED ([KIOSK_ID] ASC);
GO

-- Creating primary key on [TT_ID] in table 'TROUBLE_TICKETS'
ALTER TABLE [dbo].[TROUBLE_TICKETS]
ADD CONSTRAINT [PK_TROUBLE_TICKETS]
    PRIMARY KEY CLUSTERED ([TT_ID] ASC);
GO

-- Creating primary key on [TTU_ID] in table 'TROUBLE_DESK_USERS'
ALTER TABLE [dbo].[TROUBLE_DESK_USERS]
ADD CONSTRAINT [PK_TROUBLE_DESK_USERS]
    PRIMARY KEY CLUSTERED ([TTU_ID] ASC);
GO

-- Creating primary key on [DEVICE_ID] in table 'DEVICES'
ALTER TABLE [dbo].[DEVICES]
ADD CONSTRAINT [PK_DEVICES]
    PRIMARY KEY CLUSTERED ([DEVICE_ID] ASC);
GO

-- Creating primary key on [ID] in table 'USER_SESSIONS'
ALTER TABLE [dbo].[USER_SESSIONS]
ADD CONSTRAINT [PK_USER_SESSIONS]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [BREAK_ID] in table 'BREAKS'
ALTER TABLE [dbo].[BREAKS]
ADD CONSTRAINT [PK_BREAKS]
    PRIMARY KEY CLUSTERED ([BREAK_ID] ASC);
GO

-- Creating primary key on [ID] in table 'BREAK_TYPES'
ALTER TABLE [dbo].[BREAK_TYPES]
ADD CONSTRAINT [PK_BREAK_TYPES]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'REASSIGNMENTS'
ALTER TABLE [dbo].[REASSIGNMENTS]
ADD CONSTRAINT [PK_REASSIGNMENTS]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [MESSAGE_ID] in table 'MESSAGES'
ALTER TABLE [dbo].[MESSAGES]
ADD CONSTRAINT [PK_MESSAGES]
    PRIMARY KEY CLUSTERED ([MESSAGE_ID] ASC);
GO

-- Creating primary key on [ID] in table 'REASSIGNMENT_MOTIVES'
ALTER TABLE [dbo].[REASSIGNMENT_MOTIVES]
ADD CONSTRAINT [PK_REASSIGNMENT_MOTIVES]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'AUTO_TROUBLE_REASONS'
ALTER TABLE [dbo].[AUTO_TROUBLE_REASONS]
ADD CONSTRAINT [PK_AUTO_TROUBLE_REASONS]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ERROR_ID] in table 'ERRORS'
ALTER TABLE [dbo].[ERRORS]
ADD CONSTRAINT [PK_ERRORS]
    PRIMARY KEY CLUSTERED ([ERROR_ID] ASC);
GO

-- Creating primary key on [APPLICATION_ID] in table 'APPLICATIONS'
ALTER TABLE [dbo].[APPLICATIONS]
ADD CONSTRAINT [PK_APPLICATIONS]
    PRIMARY KEY CLUSTERED ([APPLICATION_ID] ASC);
GO

-- Creating primary key on [ID] in table 'TYPE_ERRORS'
ALTER TABLE [dbo].[TYPE_ERRORS]
ADD CONSTRAINT [PK_TYPE_ERRORS]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'PRE_GATE_DETAILS'
ALTER TABLE [dbo].[PRE_GATE_DETAILS]
ADD CONSTRAINT [PK_PRE_GATE_DETAILS]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'DAMAGES'
ALTER TABLE [dbo].[DAMAGES]
ADD CONSTRAINT [PK_DAMAGES]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TRANSACTION_TYPES'
ALTER TABLE [dbo].[TRANSACTION_TYPES]
ADD CONSTRAINT [PK_TRANSACTION_TYPES]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ACTION_ID] in table 'ACTIONS'
ALTER TABLE [dbo].[ACTIONS]
ADD CONSTRAINT [PK_ACTIONS]
    PRIMARY KEY CLUSTERED ([ACTION_ID] ASC);
GO

-- Creating primary key on [ID] in table 'TOS_PROCCESSES'
ALTER TABLE [dbo].[TOS_PROCCESSES]
ADD CONSTRAINT [PK_TOS_PROCCESSES]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [SENSOR_ID] in table 'SENSORS'
ALTER TABLE [dbo].[SENSORS]
ADD CONSTRAINT [PK_SENSORS]
    PRIMARY KEY CLUSTERED ([SENSOR_ID] ASC);
GO

-- Creating primary key on [ID] in table 'SENSOR_KIOSK_TRANSACTIONS'
ALTER TABLE [dbo].[SENSOR_KIOSK_TRANSACTIONS]
ADD CONSTRAINT [PK_SENSOR_KIOSK_TRANSACTIONS]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'LIFT_UP_BARRIERS'
ALTER TABLE [dbo].[LIFT_UP_BARRIERS]
ADD CONSTRAINT [PK_LIFT_UP_BARRIERS]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'REPRINTS'
ALTER TABLE [dbo].[REPRINTS]
ADD CONSTRAINT [PK_REPRINTS]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'BY_PASSES'
ALTER TABLE [dbo].[BY_PASSES]
ADD CONSTRAINT [PK_BY_PASSES]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'BY_PASS_AUDITS'
ALTER TABLE [dbo].[BY_PASS_AUDITS]
ADD CONSTRAINT [PK_BY_PASS_AUDITS]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID_DEPOT] in table 'DEPOT'
ALTER TABLE [dbo].[DEPOT]
ADD CONSTRAINT [PK_DEPOT]
    PRIMARY KEY CLUSTERED ([ID_DEPOT] ASC);
GO

-- Creating primary key on [ID_LINE] in table 'LINE'
ALTER TABLE [dbo].[LINE]
ADD CONSTRAINT [PK_LINE]
    PRIMARY KEY CLUSTERED ([ID_LINE] ASC);
GO

-- Creating primary key on [ID_LINE], [ID_DEPOT], [ACTIVE] in table 'LINE_DEPOTS'
ALTER TABLE [dbo].[LINE_DEPOTS]
ADD CONSTRAINT [PK_LINE_DEPOTS]
    PRIMARY KEY CLUSTERED ([ID_LINE], [ID_DEPOT], [ACTIVE] ASC);
GO

-- Creating primary key on [ID_OPERATION] in table 'STOCK_OPERATION'
ALTER TABLE [dbo].[STOCK_OPERATION]
ADD CONSTRAINT [PK_STOCK_OPERATION]
    PRIMARY KEY CLUSTERED ([ID_OPERATION] ASC);
GO

-- Creating primary key on [ID] in table 'STOCK_REGISTER'
ALTER TABLE [dbo].[STOCK_REGISTER]
ADD CONSTRAINT [PK_STOCK_REGISTER]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [MOTIVE_ID] in table 'MOTIVES'
ALTER TABLE [dbo].[MOTIVES]
ADD CONSTRAINT [PK_MOTIVES]
    PRIMARY KEY CLUSTERED ([MOTIVE_ID] ASC);
GO

-- Creating primary key on [SUB_MOTIVE_ID] in table 'SUB_MOTIVES'
ALTER TABLE [dbo].[SUB_MOTIVES]
ADD CONSTRAINT [PK_SUB_MOTIVES]
    PRIMARY KEY CLUSTERED ([SUB_MOTIVE_ID] ASC);
GO

-- Creating primary key on [TT_ID] in table 'TROUBLE_TICKETS_AUTO_TROUBLE_TICKET'
ALTER TABLE [dbo].[TROUBLE_TICKETS_AUTO_TROUBLE_TICKET]
ADD CONSTRAINT [PK_TROUBLE_TICKETS_AUTO_TROUBLE_TICKET]
    PRIMARY KEY CLUSTERED ([TT_ID] ASC);
GO

-- Creating primary key on [TT_ID] in table 'TROUBLE_TICKETS_PROCESS_TROUBLE_TICKET'
ALTER TABLE [dbo].[TROUBLE_TICKETS_PROCESS_TROUBLE_TICKET]
ADD CONSTRAINT [PK_TROUBLE_TICKETS_PROCESS_TROUBLE_TICKET]
    PRIMARY KEY CLUSTERED ([TT_ID] ASC);
GO

-- Creating primary key on [TT_ID] in table 'TROUBLE_TICKETS_MOBILE_TROUBLE_TICKET'
ALTER TABLE [dbo].[TROUBLE_TICKETS_MOBILE_TROUBLE_TICKET]
ADD CONSTRAINT [PK_TROUBLE_TICKETS_MOBILE_TROUBLE_TICKET]
    PRIMARY KEY CLUSTERED ([TT_ID] ASC);
GO

-- Creating primary key on [TT_ID] in table 'TROUBLE_TICKETS_CLIENT_APP_TRANSACTION_TROUBLE_TICKET'
ALTER TABLE [dbo].[TROUBLE_TICKETS_CLIENT_APP_TRANSACTION_TROUBLE_TICKET]
ADD CONSTRAINT [PK_TROUBLE_TICKETS_CLIENT_APP_TRANSACTION_TROUBLE_TICKET]
    PRIMARY KEY CLUSTERED ([TT_ID] ASC);
GO

-- Creating primary key on [ZONES_ZONE_ID], [TRANSACTION_TYPES_ID] in table 'ZONETRANSACTION_TYPE'
ALTER TABLE [dbo].[ZONETRANSACTION_TYPE]
ADD CONSTRAINT [PK_ZONETRANSACTION_TYPE]
    PRIMARY KEY CLUSTERED ([ZONES_ZONE_ID], [TRANSACTION_TYPES_ID] ASC);
GO

-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on [CONTAINER_ID] in table 'SEALS'
ALTER TABLE [dbo].[SEALS]
ADD CONSTRAINT [FK_CONTAINERSEAL]
    FOREIGN KEY ([CONTAINER_ID])
    REFERENCES [dbo].[CONTAINERS]
        ([CONTAINER_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CONTAINERSEAL'
CREATE INDEX [IX_FK_CONTAINERSEAL]
ON [dbo].[SEALS]
    ([CONTAINER_ID]);
GO

-- Creating foreign key on [TRANSACTION_ID] in table 'PROCESSES'
ALTER TABLE [dbo].[PROCESSES]
ADD CONSTRAINT [FK_KIOSK_TRANSACTIONPROCESS]
    FOREIGN KEY ([TRANSACTION_ID])
    REFERENCES [dbo].[KIOSK_TRANSACTIONS]
        ([TRANSACTION_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_KIOSK_TRANSACTIONPROCESS'
CREATE INDEX [IX_FK_KIOSK_TRANSACTIONPROCESS]
ON [dbo].[PROCESSES]
    ([TRANSACTION_ID]);
GO

-- Creating foreign key on [ZONE_ID] in table 'KIOSKS'
ALTER TABLE [dbo].[KIOSKS]
ADD CONSTRAINT [FK_KIOSKZONE]
    FOREIGN KEY ([ZONE_ID])
    REFERENCES [dbo].[ZONES]
        ([ZONE_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_KIOSKZONE'
CREATE INDEX [IX_FK_KIOSKZONE]
ON [dbo].[KIOSKS]
    ([ZONE_ID]);
GO

-- Creating foreign key on [KIOSK_ID] in table 'KIOSK_TRANSACTIONS'
ALTER TABLE [dbo].[KIOSK_TRANSACTIONS]
ADD CONSTRAINT [FK_KIOSK_TRANSACTIONKIOSK]
    FOREIGN KEY ([KIOSK_ID])
    REFERENCES [dbo].[KIOSKS]
        ([KIOSK_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_KIOSK_TRANSACTIONKIOSK'
CREATE INDEX [IX_FK_KIOSK_TRANSACTIONKIOSK]
ON [dbo].[KIOSK_TRANSACTIONS]
    ([KIOSK_ID]);
GO

-- Creating foreign key on [ZONE_ID] in table 'DEVICES'
ALTER TABLE [dbo].[DEVICES]
ADD CONSTRAINT [FK_DEVICEZONE]
    FOREIGN KEY ([ZONE_ID])
    REFERENCES [dbo].[ZONES]
        ([ZONE_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_DEVICEZONE'
CREATE INDEX [IX_FK_DEVICEZONE]
ON [dbo].[DEVICES]
    ([ZONE_ID]);
GO

-- Creating foreign key on [DEVICE_ID] in table 'USER_SESSIONS'
ALTER TABLE [dbo].[USER_SESSIONS]
ADD CONSTRAINT [FK_DEVICEUSER_SESSION]
    FOREIGN KEY ([DEVICE_ID])
    REFERENCES [dbo].[DEVICES]
        ([DEVICE_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_DEVICEUSER_SESSION'
CREATE INDEX [IX_FK_DEVICEUSER_SESSION]
ON [dbo].[USER_SESSIONS]
    ([DEVICE_ID]);
GO

-- Creating foreign key on [TTU_ID] in table 'USER_SESSIONS'
ALTER TABLE [dbo].[USER_SESSIONS]
ADD CONSTRAINT [FK_TROUBLE_DESK_USERUSER_SESSION]
    FOREIGN KEY ([TTU_ID])
    REFERENCES [dbo].[TROUBLE_DESK_USERS]
        ([TTU_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TROUBLE_DESK_USERUSER_SESSION'
CREATE INDEX [IX_FK_TROUBLE_DESK_USERUSER_SESSION]
ON [dbo].[USER_SESSIONS]
    ([TTU_ID]);
GO

-- Creating foreign key on [BREAK_TYPE_ID] in table 'BREAKS'
ALTER TABLE [dbo].[BREAKS]
ADD CONSTRAINT [FK_BREAK_TYPEBREAK]
    FOREIGN KEY ([BREAK_TYPE_ID])
    REFERENCES [dbo].[BREAK_TYPES]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_BREAK_TYPEBREAK'
CREATE INDEX [IX_FK_BREAK_TYPEBREAK]
ON [dbo].[BREAKS]
    ([BREAK_TYPE_ID]);
GO

-- Creating foreign key on [USER_SESSION_ID] in table 'BREAKS'
ALTER TABLE [dbo].[BREAKS]
ADD CONSTRAINT [FK_USER_SESSIONBREAK]
    FOREIGN KEY ([USER_SESSION_ID])
    REFERENCES [dbo].[USER_SESSIONS]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_USER_SESSIONBREAK'
CREATE INDEX [IX_FK_USER_SESSIONBREAK]
ON [dbo].[BREAKS]
    ([USER_SESSION_ID]);
GO

-- Creating foreign key on [USER_SESSION_ID] in table 'REASSIGNMENTS'
ALTER TABLE [dbo].[REASSIGNMENTS]
ADD CONSTRAINT [FK_REASSIGNMENTUSER_SESSION]
    FOREIGN KEY ([USER_SESSION_ID])
    REFERENCES [dbo].[USER_SESSIONS]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_REASSIGNMENTUSER_SESSION'
CREATE INDEX [IX_FK_REASSIGNMENTUSER_SESSION]
ON [dbo].[REASSIGNMENTS]
    ([USER_SESSION_ID]);
GO

-- Creating foreign key on [MESSAGE_ID] in table 'PROCESSES'
ALTER TABLE [dbo].[PROCESSES]
ADD CONSTRAINT [FK_PROCESSMESSAGE]
    FOREIGN KEY ([MESSAGE_ID])
    REFERENCES [dbo].[MESSAGES]
        ([MESSAGE_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PROCESSMESSAGE'
CREATE INDEX [IX_FK_PROCESSMESSAGE]
ON [dbo].[PROCESSES]
    ([MESSAGE_ID]);
GO

-- Creating foreign key on [MOTIVE_ID] in table 'REASSIGNMENTS'
ALTER TABLE [dbo].[REASSIGNMENTS]
ADD CONSTRAINT [FK_REASSIGNMENTREASSIGNMENT_MOTIVE]
    FOREIGN KEY ([MOTIVE_ID])
    REFERENCES [dbo].[REASSIGNMENT_MOTIVES]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_REASSIGNMENTREASSIGNMENT_MOTIVE'
CREATE INDEX [IX_FK_REASSIGNMENTREASSIGNMENT_MOTIVE]
ON [dbo].[REASSIGNMENTS]
    ([MOTIVE_ID]);
GO

-- Creating foreign key on [REASON_ID] in table 'TROUBLE_TICKETS_AUTO_TROUBLE_TICKET'
ALTER TABLE [dbo].[TROUBLE_TICKETS_AUTO_TROUBLE_TICKET]
ADD CONSTRAINT [FK_AUTO_TROUBLE_REASONAUTO_TROUBLE_TICKET]
    FOREIGN KEY ([REASON_ID])
    REFERENCES [dbo].[AUTO_TROUBLE_REASONS]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_AUTO_TROUBLE_REASONAUTO_TROUBLE_TICKET'
CREATE INDEX [IX_FK_AUTO_TROUBLE_REASONAUTO_TROUBLE_TICKET]
ON [dbo].[TROUBLE_TICKETS_AUTO_TROUBLE_TICKET]
    ([REASON_ID]);
GO

-- Creating foreign key on [USER_SESSION_ID] in table 'TROUBLE_TICKETS_AUTO_TROUBLE_TICKET'
ALTER TABLE [dbo].[TROUBLE_TICKETS_AUTO_TROUBLE_TICKET]
ADD CONSTRAINT [FK_AUTO_TROUBLE_TICKETUSER_SESSION]
    FOREIGN KEY ([USER_SESSION_ID])
    REFERENCES [dbo].[USER_SESSIONS]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_AUTO_TROUBLE_TICKETUSER_SESSION'
CREATE INDEX [IX_FK_AUTO_TROUBLE_TICKETUSER_SESSION]
ON [dbo].[TROUBLE_TICKETS_AUTO_TROUBLE_TICKET]
    ([USER_SESSION_ID]);
GO

-- Creating foreign key on [APPLICATION_ID] in table 'ERRORS'
ALTER TABLE [dbo].[ERRORS]
ADD CONSTRAINT [FK_ERRORAPPLICATION]
    FOREIGN KEY ([APPLICATION_ID])
    REFERENCES [dbo].[APPLICATIONS]
        ([APPLICATION_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ERRORAPPLICATION'
CREATE INDEX [IX_FK_ERRORAPPLICATION]
ON [dbo].[ERRORS]
    ([APPLICATION_ID]);
GO

-- Creating foreign key on [TYPE_ERROR_ID] in table 'ERRORS'
ALTER TABLE [dbo].[ERRORS]
ADD CONSTRAINT [FK_TYPE_ERRORERROR]
    FOREIGN KEY ([TYPE_ERROR_ID])
    REFERENCES [dbo].[TYPE_ERRORS]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TYPE_ERRORERROR'
CREATE INDEX [IX_FK_TYPE_ERRORERROR]
ON [dbo].[ERRORS]
    ([TYPE_ERROR_ID]);
GO

-- Creating foreign key on [CONTAINER_ID] in table 'DAMAGES'
ALTER TABLE [dbo].[DAMAGES]
ADD CONSTRAINT [FK_CONTAINERDAMAGE]
    FOREIGN KEY ([CONTAINER_ID])
    REFERENCES [dbo].[CONTAINERS]
        ([CONTAINER_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CONTAINERDAMAGE'
CREATE INDEX [IX_FK_CONTAINERDAMAGE]
ON [dbo].[DAMAGES]
    ([CONTAINER_ID]);
GO

-- Creating foreign key on [PROCESS_PROCESS_ID] in table 'TROUBLE_TICKETS_PROCESS_TROUBLE_TICKET'
ALTER TABLE [dbo].[TROUBLE_TICKETS_PROCESS_TROUBLE_TICKET]
ADD CONSTRAINT [FK_PROCESSPROCESS_TROUBLE_TICKET]
    FOREIGN KEY ([PROCESS_PROCESS_ID])
    REFERENCES [dbo].[PROCESSES]
        ([PROCESS_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PROCESSPROCESS_TROUBLE_TICKET'
CREATE INDEX [IX_FK_PROCESSPROCESS_TROUBLE_TICKET]
ON [dbo].[TROUBLE_TICKETS_PROCESS_TROUBLE_TICKET]
    ([PROCESS_PROCESS_ID]);
GO

-- Creating foreign key on [USER_SESSION_ID] in table 'TROUBLE_TICKETS_PROCESS_TROUBLE_TICKET'
ALTER TABLE [dbo].[TROUBLE_TICKETS_PROCESS_TROUBLE_TICKET]
ADD CONSTRAINT [FK_USER_SESSIONPROCESS_TROUBLE_TICKET]
    FOREIGN KEY ([USER_SESSION_ID])
    REFERENCES [dbo].[USER_SESSIONS]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_USER_SESSIONPROCESS_TROUBLE_TICKET'
CREATE INDEX [IX_FK_USER_SESSIONPROCESS_TROUBLE_TICKET]
ON [dbo].[TROUBLE_TICKETS_PROCESS_TROUBLE_TICKET]
    ([USER_SESSION_ID]);
GO

-- Creating foreign key on [TT_ID] in table 'REASSIGNMENTS'
ALTER TABLE [dbo].[REASSIGNMENTS]
ADD CONSTRAINT [FK_PROCESS_TROUBLE_TICKETREASSIGNMENT]
    FOREIGN KEY ([TT_ID])
    REFERENCES [dbo].[TROUBLE_TICKETS_PROCESS_TROUBLE_TICKET]
        ([TT_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PROCESS_TROUBLE_TICKETREASSIGNMENT'
CREATE INDEX [IX_FK_PROCESS_TROUBLE_TICKETREASSIGNMENT]
ON [dbo].[REASSIGNMENTS]
    ([TT_ID]);
GO

-- Creating foreign key on [USER_SESSION_ID] in table 'TROUBLE_TICKETS_MOBILE_TROUBLE_TICKET'
ALTER TABLE [dbo].[TROUBLE_TICKETS_MOBILE_TROUBLE_TICKET]
ADD CONSTRAINT [FK_USER_SESSIONMOBILE_TROUBLE_TICKET]
    FOREIGN KEY ([USER_SESSION_ID])
    REFERENCES [dbo].[USER_SESSIONS]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_USER_SESSIONMOBILE_TROUBLE_TICKET'
CREATE INDEX [IX_FK_USER_SESSIONMOBILE_TROUBLE_TICKET]
ON [dbo].[TROUBLE_TICKETS_MOBILE_TROUBLE_TICKET]
    ([USER_SESSION_ID]);
GO

-- Creating foreign key on [PRE_GATE_DETAIL_ID] in table 'CONTAINERS'
ALTER TABLE [dbo].[CONTAINERS]
ADD CONSTRAINT [FK_PRE_GATE_DETAILCONTAINER]
    FOREIGN KEY ([PRE_GATE_DETAIL_ID])
    REFERENCES [dbo].[PRE_GATE_DETAILS]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PRE_GATE_DETAILCONTAINER'
CREATE INDEX [IX_FK_PRE_GATE_DETAILCONTAINER]
ON [dbo].[CONTAINERS]
    ([PRE_GATE_DETAIL_ID]);
GO

-- Creating foreign key on [TRANSACTION_TYPE_ID] in table 'PRE_GATE_DETAILS'
ALTER TABLE [dbo].[PRE_GATE_DETAILS]
ADD CONSTRAINT [FK_TRANSACTION_TYPEPRE_GATE_DETAIL]
    FOREIGN KEY ([TRANSACTION_TYPE_ID])
    REFERENCES [dbo].[TRANSACTION_TYPES]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TRANSACTION_TYPEPRE_GATE_DETAIL'
CREATE INDEX [IX_FK_TRANSACTION_TYPEPRE_GATE_DETAIL]
ON [dbo].[PRE_GATE_DETAILS]
    ([TRANSACTION_TYPE_ID]);
GO

-- Creating foreign key on [DEVICE_ID] in table 'PRE_GATES'
ALTER TABLE [dbo].[PRE_GATES]
ADD CONSTRAINT [FK_PRE_GATEDEVICE]
    FOREIGN KEY ([DEVICE_ID])
    REFERENCES [dbo].[DEVICES]
        ([DEVICE_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PRE_GATEDEVICE'
CREATE INDEX [IX_FK_PRE_GATEDEVICE]
ON [dbo].[PRE_GATES]
    ([DEVICE_ID]);
GO

-- Creating foreign key on [PRE_GATE_ID] in table 'PRE_GATE_DETAILS'
ALTER TABLE [dbo].[PRE_GATE_DETAILS]
ADD CONSTRAINT [FK_PRE_GATEPRE_GATE_DETAIL]
    FOREIGN KEY ([PRE_GATE_ID])
    REFERENCES [dbo].[PRE_GATES]
        ([PRE_GATE_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PRE_GATEPRE_GATE_DETAIL'
CREATE INDEX [IX_FK_PRE_GATEPRE_GATE_DETAIL]
ON [dbo].[PRE_GATE_DETAILS]
    ([PRE_GATE_ID]);
GO

-- Creating foreign key on [ERROR_ERROR_ID] in table 'TROUBLE_TICKETS_CLIENT_APP_TRANSACTION_TROUBLE_TICKET'
ALTER TABLE [dbo].[TROUBLE_TICKETS_CLIENT_APP_TRANSACTION_TROUBLE_TICKET]
ADD CONSTRAINT [FK_ERRORCLIENT_APP_TRANSACTION_TROUBLE_TICKET]
    FOREIGN KEY ([ERROR_ERROR_ID])
    REFERENCES [dbo].[ERRORS]
        ([ERROR_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ERRORCLIENT_APP_TRANSACTION_TROUBLE_TICKET'
CREATE INDEX [IX_FK_ERRORCLIENT_APP_TRANSACTION_TROUBLE_TICKET]
ON [dbo].[TROUBLE_TICKETS_CLIENT_APP_TRANSACTION_TROUBLE_TICKET]
    ([ERROR_ERROR_ID]);
GO

-- Creating foreign key on [USER_SESSION_ID] in table 'TROUBLE_TICKETS_CLIENT_APP_TRANSACTION_TROUBLE_TICKET'
ALTER TABLE [dbo].[TROUBLE_TICKETS_CLIENT_APP_TRANSACTION_TROUBLE_TICKET]
ADD CONSTRAINT [FK_USER_SESSIONCLIENT_APP_TRANSACTION_TROUBLE_TICKET]
    FOREIGN KEY ([USER_SESSION_ID])
    REFERENCES [dbo].[USER_SESSIONS]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_USER_SESSIONCLIENT_APP_TRANSACTION_TROUBLE_TICKET'
CREATE INDEX [IX_FK_USER_SESSIONCLIENT_APP_TRANSACTION_TROUBLE_TICKET]
ON [dbo].[TROUBLE_TICKETS_CLIENT_APP_TRANSACTION_TROUBLE_TICKET]
    ([USER_SESSION_ID]);
GO

-- Creating foreign key on [ZONES_ZONE_ID] in table 'ZONETRANSACTION_TYPE'
ALTER TABLE [dbo].[ZONETRANSACTION_TYPE]
ADD CONSTRAINT [FK_ZONETRANSACTION_TYPE_ZONE]
    FOREIGN KEY ([ZONES_ZONE_ID])
    REFERENCES [dbo].[ZONES]
        ([ZONE_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating foreign key on [TRANSACTION_TYPES_ID] in table 'ZONETRANSACTION_TYPE'
ALTER TABLE [dbo].[ZONETRANSACTION_TYPE]
ADD CONSTRAINT [FK_ZONETRANSACTION_TYPE_TRANSACTION_TYPE]
    FOREIGN KEY ([TRANSACTION_TYPES_ID])
    REFERENCES [dbo].[TRANSACTION_TYPES]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ZONETRANSACTION_TYPE_TRANSACTION_TYPE'
CREATE INDEX [IX_FK_ZONETRANSACTION_TYPE_TRANSACTION_TYPE]
ON [dbo].[ZONETRANSACTION_TYPE]
    ([TRANSACTION_TYPES_ID]);
GO

-- Creating foreign key on [PRE_GATE_ID] in table 'KIOSK_TRANSACTIONS'
ALTER TABLE [dbo].[KIOSK_TRANSACTIONS]
ADD CONSTRAINT [FK_PRE_GATEKIOSK_TRANSACTION]
    FOREIGN KEY ([PRE_GATE_ID])
    REFERENCES [dbo].[PRE_GATES]
        ([PRE_GATE_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PRE_GATEKIOSK_TRANSACTION'
CREATE INDEX [IX_FK_PRE_GATEKIOSK_TRANSACTION]
ON [dbo].[KIOSK_TRANSACTIONS]
    ([PRE_GATE_ID]);
GO

-- Creating foreign key on [TT_ID] in table 'ACTIONS'
ALTER TABLE [dbo].[ACTIONS]
ADD CONSTRAINT [FK_ACTIONPROCESS_TROUBLE_TICKET]
    FOREIGN KEY ([TT_ID])
    REFERENCES [dbo].[TROUBLE_TICKETS_PROCESS_TROUBLE_TICKET]
        ([TT_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ACTIONPROCESS_TROUBLE_TICKET'
CREATE INDEX [IX_FK_ACTIONPROCESS_TROUBLE_TICKET]
ON [dbo].[ACTIONS]
    ([TT_ID]);
GO

-- Creating foreign key on [ZONE_ID] in table 'TROUBLE_TICKETS_CLIENT_APP_TRANSACTION_TROUBLE_TICKET'
ALTER TABLE [dbo].[TROUBLE_TICKETS_CLIENT_APP_TRANSACTION_TROUBLE_TICKET]
ADD CONSTRAINT [FK_ZONECLIENT_APP_TRANSACTION_TROUBLE_TICKET]
    FOREIGN KEY ([ZONE_ID])
    REFERENCES [dbo].[ZONES]
        ([ZONE_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ZONECLIENT_APP_TRANSACTION_TROUBLE_TICKET'
CREATE INDEX [IX_FK_ZONECLIENT_APP_TRANSACTION_TROUBLE_TICKET]
ON [dbo].[TROUBLE_TICKETS_CLIENT_APP_TRANSACTION_TROUBLE_TICKET]
    ([ZONE_ID]);
GO

-- Creating foreign key on [PRE_GATE_ID] in table 'TOS_PROCCESSES'
ALTER TABLE [dbo].[TOS_PROCCESSES]
ADD CONSTRAINT [FK_TOS_PROCCESSPRE_GATE]
    FOREIGN KEY ([PRE_GATE_ID])
    REFERENCES [dbo].[PRE_GATES]
        ([PRE_GATE_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TOS_PROCCESSPRE_GATE'
CREATE INDEX [IX_FK_TOS_PROCCESSPRE_GATE]
ON [dbo].[TOS_PROCCESSES]
    ([PRE_GATE_ID]);
GO

-- Creating foreign key on [MOBILE_TROUBLE_TICKET_TT_ID] in table 'TOS_PROCCESSES'
ALTER TABLE [dbo].[TOS_PROCCESSES]
ADD CONSTRAINT [FK_MOBILE_TROUBLE_TICKETTOS_PROCCESS]
    FOREIGN KEY ([MOBILE_TROUBLE_TICKET_TT_ID])
    REFERENCES [dbo].[TROUBLE_TICKETS_MOBILE_TROUBLE_TICKET]
        ([TT_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_MOBILE_TROUBLE_TICKETTOS_PROCCESS'
CREATE INDEX [IX_FK_MOBILE_TROUBLE_TICKETTOS_PROCCESS]
ON [dbo].[TOS_PROCCESSES]
    ([MOBILE_TROUBLE_TICKET_TT_ID]);
GO

-- Creating foreign key on [SENSOR_ID] in table 'SENSOR_KIOSK_TRANSACTIONS'
ALTER TABLE [dbo].[SENSOR_KIOSK_TRANSACTIONS]
ADD CONSTRAINT [FK_SENSORSENSOR_KIOSK_TRANSACTION]
    FOREIGN KEY ([SENSOR_ID])
    REFERENCES [dbo].[SENSORS]
        ([SENSOR_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_SENSORSENSOR_KIOSK_TRANSACTION'
CREATE INDEX [IX_FK_SENSORSENSOR_KIOSK_TRANSACTION]
ON [dbo].[SENSOR_KIOSK_TRANSACTIONS]
    ([SENSOR_ID]);
GO

-- Creating foreign key on [TRANSACTION_ID] in table 'SENSOR_KIOSK_TRANSACTIONS'
ALTER TABLE [dbo].[SENSOR_KIOSK_TRANSACTIONS]
ADD CONSTRAINT [FK_KIOSK_TRANSACTIONSENSOR_KIOSK_TRANSACTION]
    FOREIGN KEY ([TRANSACTION_ID])
    REFERENCES [dbo].[KIOSK_TRANSACTIONS]
        ([TRANSACTION_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_KIOSK_TRANSACTIONSENSOR_KIOSK_TRANSACTION'
CREATE INDEX [IX_FK_KIOSK_TRANSACTIONSENSOR_KIOSK_TRANSACTION]
ON [dbo].[SENSOR_KIOSK_TRANSACTIONS]
    ([TRANSACTION_ID]);
GO

-- Creating foreign key on [KIOSK_ID] in table 'LIFT_UP_BARRIERS'
ALTER TABLE [dbo].[LIFT_UP_BARRIERS]
ADD CONSTRAINT [FK_KIOSKLIFT_UP_BARRIER]
    FOREIGN KEY ([KIOSK_ID])
    REFERENCES [dbo].[KIOSKS]
        ([KIOSK_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_KIOSKLIFT_UP_BARRIER'
CREATE INDEX [IX_FK_KIOSKLIFT_UP_BARRIER]
ON [dbo].[LIFT_UP_BARRIERS]
    ([KIOSK_ID]);
GO

-- Creating foreign key on [TTU_ID] in table 'LIFT_UP_BARRIERS'
ALTER TABLE [dbo].[LIFT_UP_BARRIERS]
ADD CONSTRAINT [FK_TROUBLE_DESK_USERLIFT_UP_BARRIER]
    FOREIGN KEY ([TTU_ID])
    REFERENCES [dbo].[TROUBLE_DESK_USERS]
        ([TTU_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TROUBLE_DESK_USERLIFT_UP_BARRIER'
CREATE INDEX [IX_FK_TROUBLE_DESK_USERLIFT_UP_BARRIER]
ON [dbo].[LIFT_UP_BARRIERS]
    ([TTU_ID]);
GO

-- Creating foreign key on [ZONE_ID] in table 'TROUBLE_TICKETS_MOBILE_TROUBLE_TICKET'
ALTER TABLE [dbo].[TROUBLE_TICKETS_MOBILE_TROUBLE_TICKET]
ADD CONSTRAINT [FK_MOBILE_TROUBLE_TICKETZONE]
    FOREIGN KEY ([ZONE_ID])
    REFERENCES [dbo].[ZONES]
        ([ZONE_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_MOBILE_TROUBLE_TICKETZONE'
CREATE INDEX [IX_FK_MOBILE_TROUBLE_TICKETZONE]
ON [dbo].[TROUBLE_TICKETS_MOBILE_TROUBLE_TICKET]
    ([ZONE_ID]);
GO

-- Creating foreign key on [PRE_GATE_ID] in table 'TROUBLE_TICKETS_MOBILE_TROUBLE_TICKET'
ALTER TABLE [dbo].[TROUBLE_TICKETS_MOBILE_TROUBLE_TICKET]
ADD CONSTRAINT [FK_PRE_GATETROUBLE_TICKETS_MOBILE_TROUBLE_TICKET]
    FOREIGN KEY ([PRE_GATE_ID])
    REFERENCES [dbo].[PRE_GATES]
        ([PRE_GATE_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PRE_GATETROUBLE_TICKETS_MOBILE_TROUBLE_TICKET'
CREATE INDEX [IX_FK_PRE_GATETROUBLE_TICKETS_MOBILE_TROUBLE_TICKET]
ON [dbo].[TROUBLE_TICKETS_MOBILE_TROUBLE_TICKET]
    ([PRE_GATE_ID]);
GO

-- Creating foreign key on [TTU_ID] in table 'REPRINTS'
ALTER TABLE [dbo].[REPRINTS]
ADD CONSTRAINT [FK_REPRINTTROUBLE_DESK_USER]
    FOREIGN KEY ([TTU_ID])
    REFERENCES [dbo].[TROUBLE_DESK_USERS]
        ([TTU_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_REPRINTTROUBLE_DESK_USER'
CREATE INDEX [IX_FK_REPRINTTROUBLE_DESK_USER]
ON [dbo].[REPRINTS]
    ([TTU_ID]);
GO

-- Creating foreign key on [PRE_GATE_ID] in table 'REPRINTS'
ALTER TABLE [dbo].[REPRINTS]
ADD CONSTRAINT [FK_REPRINTPRE_GATE]
    FOREIGN KEY ([PRE_GATE_ID])
    REFERENCES [dbo].[PRE_GATES]
        ([PRE_GATE_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_REPRINTPRE_GATE'
CREATE INDEX [IX_FK_REPRINTPRE_GATE]
ON [dbo].[REPRINTS]
    ([PRE_GATE_ID]);
GO

-- Creating foreign key on [KIOSK_ID] in table 'REPRINTS'
ALTER TABLE [dbo].[REPRINTS]
ADD CONSTRAINT [FK_REPRINTKIOSK]
    FOREIGN KEY ([KIOSK_ID])
    REFERENCES [dbo].[KIOSKS]
        ([KIOSK_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_REPRINTKIOSK'
CREATE INDEX [IX_FK_REPRINTKIOSK]
ON [dbo].[REPRINTS]
    ([KIOSK_ID]);
GO

-- Creating foreign key on [TTU_ID] in table 'BY_PASS_AUDITS'
ALTER TABLE [dbo].[BY_PASS_AUDITS]
ADD CONSTRAINT [FK_TROUBLE_DESK_USERBY_PASS_AUDIT]
    FOREIGN KEY ([TTU_ID])
    REFERENCES [dbo].[TROUBLE_DESK_USERS]
        ([TTU_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TROUBLE_DESK_USERBY_PASS_AUDIT'
CREATE INDEX [IX_FK_TROUBLE_DESK_USERBY_PASS_AUDIT]
ON [dbo].[BY_PASS_AUDITS]
    ([TTU_ID]);
GO

-- Creating foreign key on [BY_PASS_ID] in table 'BY_PASS_AUDITS'
ALTER TABLE [dbo].[BY_PASS_AUDITS]
ADD CONSTRAINT [FK_BY_PASSBY_PASS_AUDIT]
    FOREIGN KEY ([BY_PASS_ID])
    REFERENCES [dbo].[BY_PASSES]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_BY_PASSBY_PASS_AUDIT'
CREATE INDEX [IX_FK_BY_PASSBY_PASS_AUDIT]
ON [dbo].[BY_PASS_AUDITS]
    ([BY_PASS_ID]);
GO

-- Creating foreign key on [PRE_GATE_PRE_GATE_ID] in table 'BY_PASSES'
ALTER TABLE [dbo].[BY_PASSES]
ADD CONSTRAINT [FK_PRE_GATEBY_PASS]
    FOREIGN KEY ([PRE_GATE_PRE_GATE_ID])
    REFERENCES [dbo].[PRE_GATES]
        ([PRE_GATE_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PRE_GATEBY_PASS'
CREATE INDEX [IX_FK_PRE_GATEBY_PASS]
ON [dbo].[BY_PASSES]
    ([PRE_GATE_PRE_GATE_ID]);
GO

-- Creating foreign key on [ID_DEPOT] in table 'LINE_DEPOTS'
ALTER TABLE [dbo].[LINE_DEPOTS]
ADD CONSTRAINT [FK__LINE_DEPO__ID_DE__6F357288]
    FOREIGN KEY ([ID_DEPOT])
    REFERENCES [dbo].[DEPOT]
        ([ID_DEPOT])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK__LINE_DEPO__ID_DE__6F357288'
CREATE INDEX [IX_FK__LINE_DEPO__ID_DE__6F357288]
ON [dbo].[LINE_DEPOTS]
    ([ID_DEPOT]);
GO

-- Creating foreign key on [ID_DEPOT] in table 'STOCK_REGISTER'
ALTER TABLE [dbo].[STOCK_REGISTER]
ADD CONSTRAINT [FK__STOCK_REG__ID_DE__79B300FB]
    FOREIGN KEY ([ID_DEPOT])
    REFERENCES [dbo].[DEPOT]
        ([ID_DEPOT])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK__STOCK_REG__ID_DE__79B300FB'
CREATE INDEX [IX_FK__STOCK_REG__ID_DE__79B300FB]
ON [dbo].[STOCK_REGISTER]
    ([ID_DEPOT]);
GO

-- Creating foreign key on [ID_LINE] in table 'LINE_DEPOTS'
ALTER TABLE [dbo].[LINE_DEPOTS]
ADD CONSTRAINT [FK__LINE_DEPO__ID_LI__6E414E4F]
    FOREIGN KEY ([ID_LINE])
    REFERENCES [dbo].[LINE]
        ([ID_LINE])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating foreign key on [ID_LINE] in table 'STOCK_REGISTER'
ALTER TABLE [dbo].[STOCK_REGISTER]
ADD CONSTRAINT [FK__STOCK_REG__ID_LI__78BEDCC2]
    FOREIGN KEY ([ID_LINE])
    REFERENCES [dbo].[LINE]
        ([ID_LINE])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK__STOCK_REG__ID_LI__78BEDCC2'
CREATE INDEX [IX_FK__STOCK_REG__ID_LI__78BEDCC2]
ON [dbo].[STOCK_REGISTER]
    ([ID_LINE]);
GO

-- Creating foreign key on [ID_OPERATION] in table 'STOCK_REGISTER'
ALTER TABLE [dbo].[STOCK_REGISTER]
ADD CONSTRAINT [FK__STOCK_REG__ID_OP__7AA72534]
    FOREIGN KEY ([ID_OPERATION])
    REFERENCES [dbo].[STOCK_OPERATION]
        ([ID_OPERATION])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK__STOCK_REG__ID_OP__7AA72534'
CREATE INDEX [IX_FK__STOCK_REG__ID_OP__7AA72534]
ON [dbo].[STOCK_REGISTER]
    ([ID_OPERATION]);
GO

-- Creating foreign key on [MOTIVES_ID] in table 'SUB_MOTIVES'
ALTER TABLE [dbo].[SUB_MOTIVES]
ADD CONSTRAINT [FK_MOTIVESUB_MOTIVE]
    FOREIGN KEY ([MOTIVES_ID])
    REFERENCES [dbo].[MOTIVES]
        ([MOTIVE_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_MOTIVESUB_MOTIVE'
CREATE INDEX [IX_FK_MOTIVESUB_MOTIVE]
ON [dbo].[SUB_MOTIVES]
    ([MOTIVES_ID]);
GO

-- Creating foreign key on [PRE_GATE_ID] in table 'STOCK_REGISTER'
ALTER TABLE [dbo].[STOCK_REGISTER]
ADD CONSTRAINT [FK_STOCK_PREGATE_COST]
    FOREIGN KEY ([PRE_GATE_ID])
    REFERENCES [dbo].[PRE_GATES]
        ([PRE_GATE_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_STOCK_PREGATE_COST'
CREATE INDEX [IX_FK_STOCK_PREGATE_COST]
ON [dbo].[STOCK_REGISTER]
    ([PRE_GATE_ID]);
GO

-- Creating foreign key on [TT_ID] in table 'TROUBLE_TICKETS_AUTO_TROUBLE_TICKET'
ALTER TABLE [dbo].[TROUBLE_TICKETS_AUTO_TROUBLE_TICKET]
ADD CONSTRAINT [FK_AUTO_TROUBLE_TICKET_inherits_TROUBLE_TICKET]
    FOREIGN KEY ([TT_ID])
    REFERENCES [dbo].[TROUBLE_TICKETS]
        ([TT_ID])
    ON DELETE CASCADE ON UPDATE NO ACTION;
GO

-- Creating foreign key on [TT_ID] in table 'TROUBLE_TICKETS_PROCESS_TROUBLE_TICKET'
ALTER TABLE [dbo].[TROUBLE_TICKETS_PROCESS_TROUBLE_TICKET]
ADD CONSTRAINT [FK_PROCESS_TROUBLE_TICKET_inherits_TROUBLE_TICKET]
    FOREIGN KEY ([TT_ID])
    REFERENCES [dbo].[TROUBLE_TICKETS]
        ([TT_ID])
    ON DELETE CASCADE ON UPDATE NO ACTION;
GO

-- Creating foreign key on [TT_ID] in table 'TROUBLE_TICKETS_MOBILE_TROUBLE_TICKET'
ALTER TABLE [dbo].[TROUBLE_TICKETS_MOBILE_TROUBLE_TICKET]
ADD CONSTRAINT [FK_MOBILE_TROUBLE_TICKET_inherits_TROUBLE_TICKET]
    FOREIGN KEY ([TT_ID])
    REFERENCES [dbo].[TROUBLE_TICKETS]
        ([TT_ID])
    ON DELETE CASCADE ON UPDATE NO ACTION;
GO

-- Creating foreign key on [TT_ID] in table 'TROUBLE_TICKETS_CLIENT_APP_TRANSACTION_TROUBLE_TICKET'
ALTER TABLE [dbo].[TROUBLE_TICKETS_CLIENT_APP_TRANSACTION_TROUBLE_TICKET]
ADD CONSTRAINT [FK_CLIENT_APP_TRANSACTION_TROUBLE_TICKET_inherits_TROUBLE_TICKET]
    FOREIGN KEY ([TT_ID])
    REFERENCES [dbo].[TROUBLE_TICKETS]
        ([TT_ID])
    ON DELETE CASCADE ON UPDATE NO ACTION;
GO

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------