//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaInfraestructura.Nucleo.Infraestructura.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using RECEPTIO.CapaDominio.Nucleo.Entidades;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ModeloReceptioContainer : DbContext
    {
        public ModeloReceptioContainer()
            : base("name=ModeloReceptioContainer")
        {
    	    Configuration.LazyLoadingEnabled = true;
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PRE_GATE> PRE_GATES { get; set; }
        public virtual DbSet<CONTAINER> CONTAINERS { get; set; }
        public virtual DbSet<SEAL> SEALS { get; set; }
        public virtual DbSet<KIOSK_TRANSACTION> KIOSK_TRANSACTIONS { get; set; }
        public virtual DbSet<PROCESS> PROCESSES { get; set; }
        public virtual DbSet<ZONE> ZONES { get; set; }
        public virtual DbSet<KIOSK> KIOSKS { get; set; }
        public virtual DbSet<TROUBLE_TICKET> TROUBLE_TICKETS { get; set; }
        public virtual DbSet<TROUBLE_DESK_USER> TROUBLE_DESK_USERS { get; set; }
        public virtual DbSet<DEVICE> DEVICES { get; set; }
        public virtual DbSet<USER_SESSION> USER_SESSIONS { get; set; }
        public virtual DbSet<BREAK> BREAKS { get; set; }
        public virtual DbSet<BREAK_TYPE> BREAK_TYPES { get; set; }
        public virtual DbSet<REASSIGNMENT> REASSIGNMENTS { get; set; }
        public virtual DbSet<MESSAGE> MESSAGES { get; set; }
        public virtual DbSet<REASSIGNMENT_MOTIVE> REASSIGNMENT_MOTIVES { get; set; }
        public virtual DbSet<AUTO_TROUBLE_REASON> AUTO_TROUBLE_REASONS { get; set; }
        public virtual DbSet<ERROR> ERRORS { get; set; }
        public virtual DbSet<APPLICATION> APPLICATIONS { get; set; }
        public virtual DbSet<TYPE_ERROR> TYPE_ERRORS { get; set; }
        public virtual DbSet<PRE_GATE_DETAIL> PRE_GATE_DETAILS { get; set; }
        public virtual DbSet<DAMAGE> DAMAGES { get; set; }
        public virtual DbSet<TRANSACTION_TYPE> TRANSACTION_TYPES { get; set; }
        public virtual DbSet<ACTION> ACTIONS { get; set; }
        public virtual DbSet<TOS_PROCCESS> TOS_PROCCESSES { get; set; }
        public virtual DbSet<SENSOR> SENSORS { get; set; }
        public virtual DbSet<SENSOR_KIOSK_TRANSACTION> SENSOR_KIOSK_TRANSACTIONS { get; set; }
        public virtual DbSet<LIFT_UP_BARRIER> LIFT_UP_BARRIERS { get; set; }
        public virtual DbSet<REPRINT> REPRINTS { get; set; }
        public virtual DbSet<BY_PASS> BY_PASSES { get; set; }
        public virtual DbSet<BY_PASS_AUDIT> BY_PASS_AUDITS { get; set; }
        public virtual DbSet<DEPOT> DEPOT { get; set; }
        public virtual DbSet<LINE> LINE { get; set; }
        public virtual DbSet<LINE_DEPOTS> LINE_DEPOTS { get; set; }
        public virtual DbSet<STOCK_OPERATION> STOCK_OPERATION { get; set; }
        public virtual DbSet<STOCK_REGISTER> STOCK_REGISTER { get; set; }
        public virtual DbSet<MOTIVE> MOTIVES { get; set; }
        public virtual DbSet<SUB_MOTIVE> SUB_MOTIVES { get; set; }
    
        public virtual ObjectResult<mb_add_ecuapass_transaccion_Result> mb_add_ecuapass_transaccion(Nullable<long> cODIGO_CARGA, string cODIGO_TIPO_CARGA, string oBJETO_SOLICITA, string uSUARIO_SOLICITA, string cONTENEDOR, string mRN, string mSN, string hSN, string nUMERO_ENTREGA, string cOMENTARIOS)
        {
            var cODIGO_CARGAParameter = cODIGO_CARGA.HasValue ?
                new ObjectParameter("CODIGO_CARGA", cODIGO_CARGA) :
                new ObjectParameter("CODIGO_CARGA", typeof(long));
    
            var cODIGO_TIPO_CARGAParameter = cODIGO_TIPO_CARGA != null ?
                new ObjectParameter("CODIGO_TIPO_CARGA", cODIGO_TIPO_CARGA) :
                new ObjectParameter("CODIGO_TIPO_CARGA", typeof(string));
    
            var oBJETO_SOLICITAParameter = oBJETO_SOLICITA != null ?
                new ObjectParameter("OBJETO_SOLICITA", oBJETO_SOLICITA) :
                new ObjectParameter("OBJETO_SOLICITA", typeof(string));
    
            var uSUARIO_SOLICITAParameter = uSUARIO_SOLICITA != null ?
                new ObjectParameter("USUARIO_SOLICITA", uSUARIO_SOLICITA) :
                new ObjectParameter("USUARIO_SOLICITA", typeof(string));
    
            var cONTENEDORParameter = cONTENEDOR != null ?
                new ObjectParameter("CONTENEDOR", cONTENEDOR) :
                new ObjectParameter("CONTENEDOR", typeof(string));
    
            var mRNParameter = mRN != null ?
                new ObjectParameter("MRN", mRN) :
                new ObjectParameter("MRN", typeof(string));
    
            var mSNParameter = mSN != null ?
                new ObjectParameter("MSN", mSN) :
                new ObjectParameter("MSN", typeof(string));
    
            var hSNParameter = hSN != null ?
                new ObjectParameter("HSN", hSN) :
                new ObjectParameter("HSN", typeof(string));
    
            var nUMERO_ENTREGAParameter = nUMERO_ENTREGA != null ?
                new ObjectParameter("NUMERO_ENTREGA", nUMERO_ENTREGA) :
                new ObjectParameter("NUMERO_ENTREGA", typeof(string));
    
            var cOMENTARIOSParameter = cOMENTARIOS != null ?
                new ObjectParameter("COMENTARIOS", cOMENTARIOS) :
                new ObjectParameter("COMENTARIOS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<mb_add_ecuapass_transaccion_Result>("mb_add_ecuapass_transaccion", cODIGO_CARGAParameter, cODIGO_TIPO_CARGAParameter, oBJETO_SOLICITAParameter, uSUARIO_SOLICITAParameter, cONTENEDORParameter, mRNParameter, mSNParameter, hSNParameter, nUMERO_ENTREGAParameter, cOMENTARIOSParameter);
        }
    
        public virtual ObjectResult<mb_get_ecuapass_message_pass_Result> mb_get_ecuapass_message_pass(string ref_num)
        {
            var ref_numParameter = ref_num != null ?
                new ObjectParameter("ref_num", ref_num) :
                new ObjectParameter("ref_num", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<mb_get_ecuapass_message_pass_Result>("mb_get_ecuapass_message_pass", ref_numParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> mb_get_gkey_cont(string lv_CONTENEDOR)
        {
            var lv_CONTENEDORParameter = lv_CONTENEDOR != null ?
                new ObjectParameter("lv_CONTENEDOR", lv_CONTENEDOR) :
                new ObjectParameter("lv_CONTENEDOR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("mb_get_gkey_cont", lv_CONTENEDORParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> mb_get_gkey_cont_mty(string lv_CONTENEDOR)
        {
            var lv_CONTENEDORParameter = lv_CONTENEDOR != null ?
                new ObjectParameter("lv_CONTENEDOR", lv_CONTENEDOR) :
                new ObjectParameter("lv_CONTENEDOR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("mb_get_gkey_cont_mty", lv_CONTENEDORParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> mb_get_gkey_cont_yard(string lv_CONTENEDOR)
        {
            var lv_CONTENEDORParameter = lv_CONTENEDOR != null ?
                new ObjectParameter("lv_CONTENEDOR", lv_CONTENEDOR) :
                new ObjectParameter("lv_CONTENEDOR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("mb_get_gkey_cont_yard", lv_CONTENEDORParameter);
        }
    
        public virtual ObjectResult<string> mb_get_status_n4(Nullable<decimal> pRE_GATE)
        {
            var pRE_GATEParameter = pRE_GATE.HasValue ?
                new ObjectParameter("PRE_GATE", pRE_GATE) :
                new ObjectParameter("PRE_GATE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("mb_get_status_n4", pRE_GATEParameter);
        }
    
        public virtual ObjectResult<string> mb_get_status_n4_placa(string pLACA)
        {
            var pLACAParameter = pLACA != null ?
                new ObjectParameter("PLACA", pLACA) :
                new ObjectParameter("PLACA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("mb_get_status_n4_placa", pLACAParameter);
        }
    
        public virtual ObjectResult<mb_get_valida_smdt_Result> mb_get_valida_smdt(string ref_num)
        {
            var ref_numParameter = ref_num != null ?
                new ObjectParameter("ref_num", ref_num) :
                new ObjectParameter("ref_num", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<mb_get_valida_smdt_Result>("mb_get_valida_smdt", ref_numParameter);
        }
    
        public virtual ObjectResult<string> mb_get_validaciones(string i_opcion, string i_StrValor, Nullable<int> i_IntValor, Nullable<long> i_BigintValor)
        {
            var i_opcionParameter = i_opcion != null ?
                new ObjectParameter("i_opcion", i_opcion) :
                new ObjectParameter("i_opcion", typeof(string));
    
            var i_StrValorParameter = i_StrValor != null ?
                new ObjectParameter("i_StrValor", i_StrValor) :
                new ObjectParameter("i_StrValor", typeof(string));
    
            var i_IntValorParameter = i_IntValor.HasValue ?
                new ObjectParameter("i_IntValor", i_IntValor) :
                new ObjectParameter("i_IntValor", typeof(int));
    
            var i_BigintValorParameter = i_BigintValor.HasValue ?
                new ObjectParameter("i_BigintValor", i_BigintValor) :
                new ObjectParameter("i_BigintValor", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("mb_get_validaciones", i_opcionParameter, i_StrValorParameter, i_IntValorParameter, i_BigintValorParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> mb_secuencia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("mb_secuencia");
        }
    
        public virtual ObjectResult<Nullable<byte>> mb_set_estate_smdt_transaccion(string key, string user, string causa)
        {
            var keyParameter = key != null ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(string));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var causaParameter = causa != null ?
                new ObjectParameter("causa", causa) :
                new ObjectParameter("causa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<byte>>("mb_set_estate_smdt_transaccion", keyParameter, userParameter, causaParameter);
        }
    }
}
