//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.Transaction.ServiciosDominio {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RECEPTIO.CapaDominio.Transaction.ServiciosDominio.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 22.
        /// </summary>
        internal static string MensajeAduana {
            get {
                return ResourceManager.GetString("MensajeAduana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3.
        /// </summary>
        internal static string MensajeConcurrencia {
            get {
                return ResourceManager.GetString("MensajeConcurrencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 26.
        /// </summary>
        internal static string MensajeContendorNoEstaEnPatio {
            get {
                return ResourceManager.GetString("MensajeContendorNoEstaEnPatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2.
        /// </summary>
        internal static string MensajeMultiplesPreGates {
            get {
                return ResourceManager.GetString("MensajeMultiplesPreGates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 18.
        /// </summary>
        internal static string MensajeNoExisteCodigo {
            get {
                return ResourceManager.GetString("MensajeNoExisteCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 20.
        /// </summary>
        internal static string MensajeNoExisteEntradaQuiosco {
            get {
                return ResourceManager.GetString("MensajeNoExisteEntradaQuiosco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 21.
        /// </summary>
        internal static string MensajeNoExistenciaContenedor {
            get {
                return ResourceManager.GetString("MensajeNoExistenciaContenedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        internal static string MensajeNoExistePreGate {
            get {
                return ResourceManager.GetString("MensajeNoExistePreGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 31.
        /// </summary>
        internal static string MensajePesaje {
            get {
                return ResourceManager.GetString("MensajePesaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4.
        /// </summary>
        internal static string MensajePreGateOk {
            get {
                return ResourceManager.GetString("MensajePreGateOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 19.
        /// </summary>
        internal static string MensajeSalidaExistente {
            get {
                return ResourceManager.GetString("MensajeSalidaExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 24.
        /// </summary>
        internal static string MensajeTipoTransaccionesNoContempladas {
            get {
                return ResourceManager.GetString("MensajeTipoTransaccionesNoContempladas", resourceCulture);
            }
        }
    }
}
