//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.TransactionEmpty.ServiciosDominio {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RECEPTIO.CapaDominio.TransactionEmpty.ServiciosDominio.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 26.
        /// </summary>
        internal static string MensajeContendorNoEstaEnPatio {
            get {
                return ResourceManager.GetString("MensajeContendorNoEstaEnPatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 36.
        /// </summary>
        internal static string MensajeErrorImdt {
            get {
                return ResourceManager.GetString("MensajeErrorImdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 14.
        /// </summary>
        internal static string MensajeErrorN4 {
            get {
                return ResourceManager.GetString("MensajeErrorN4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 38.
        /// </summary>
        internal static string MensajeErrorSmdt {
            get {
                return ResourceManager.GetString("MensajeErrorSmdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 35.
        /// </summary>
        internal static string MensajeImdtOk {
            get {
                return ResourceManager.GetString("MensajeImdtOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 13.
        /// </summary>
        internal static string MensajeN4Ok {
            get {
                return ResourceManager.GetString("MensajeN4Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 33.
        /// </summary>
        internal static string MensajeNoExisteCodigo {
            get {
                return ResourceManager.GetString("MensajeNoExisteCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 20.
        /// </summary>
        internal static string MensajeNoExisteEntradaQuiosco {
            get {
                return ResourceManager.GetString("MensajeNoExisteEntradaQuiosco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4.
        /// </summary>
        internal static string MensajePreGateOk {
            get {
                return ResourceManager.GetString("MensajePreGateOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 19.
        /// </summary>
        internal static string MensajeSalidaExistente {
            get {
                return ResourceManager.GetString("MensajeSalidaExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 37.
        /// </summary>
        internal static string MensajeSmdtOk {
            get {
                return ResourceManager.GetString("MensajeSmdtOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 34.
        /// </summary>
        internal static string MensajeTipoTransaccionesNoContempladas {
            get {
                return ResourceManager.GetString("MensajeTipoTransaccionesNoContempladas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 40.
        /// </summary>
        internal static string MensajeVisitaActivaN4 {
            get {
                return ResourceManager.GetString("MensajeVisitaActivaN4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 39.
        /// </summary>
        internal static string MensajeYaEfectuoDespacho {
            get {
                return ResourceManager.GetString("MensajeYaEfectuoDespacho", resourceCulture);
            }
        }
    }
}
