//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.Nucleo.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class ACTION
    {
        [DataMember]
        public int ACTION_ID { get; set; }
        [DataMember]
        public string ACTION_NAME { get; set; }
        [DataMember]
        public System.DateTime ACTION_DATE { get; set; }
        [DataMember]
        public long TT_ID { get; set; }
    
    	[DataMember]
        public virtual PROCESS_TROUBLE_TICKET PROCESS_TROUBLE_TICKET { get; set; }
    }
}
