//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.Nucleo.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class AUTO_TROUBLE_TICKET : TROUBLE_TICKET
    {
        [DataMember]
        public int REASON_ID { get; set; }
        [DataMember]
        public long USER_SESSION_ID { get; set; }
    
    	[DataMember]
        public virtual AUTO_TROUBLE_REASON AUTO_TROUBLE_REASON { get; set; }
    	[DataMember]
        public virtual USER_SESSION USER_SESSION { get; set; }
    }
}
