//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.Nucleo.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class BREAK
    {
        [DataMember]
        public int BREAK_ID { get; set; }
        [DataMember]
        public System.DateTime START_BREAK_DATE { get; set; }
        [DataMember]
        public Nullable<System.DateTime> FINISH_BREAK_DATE { get; set; }
        [DataMember]
        public byte BREAK_TYPE_ID { get; set; }
        [DataMember]
        public long USER_SESSION_ID { get; set; }
        [DataMember]
        public bool IS_RECYCLED { get; set; }
    
    	[DataMember]
        public virtual BREAK_TYPE BREAK_TYPE { get; set; }
    	[DataMember]
        public virtual USER_SESSION USER_SESSION { get; set; }
    }
}
