//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.Nucleo.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class BY_PASS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BY_PASS()
        {
            this.BY_PASS_AUDITS = new HashSet<BY_PASS_AUDIT>();
        }
    
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public string REASON { get; set; }
        [DataMember]
        public bool IS_ENABLED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<BY_PASS_AUDIT> BY_PASS_AUDITS { get; set; }
    	[DataMember]
        public virtual PRE_GATE PRE_GATE { get; set; }
    }
}
