//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.Nucleo.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class BY_PASS_AUDIT
    {
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public System.DateTime DATE { get; set; }
        [DataMember]
        public string FIELD { get; set; }
        [DataMember]
        public string OLD_VALUE { get; set; }
        [DataMember]
        public string NEW_VALUE { get; set; }
        [DataMember]
        public int TTU_ID { get; set; }
        [DataMember]
        public int BY_PASS_ID { get; set; }
    
    	[DataMember]
        public virtual TROUBLE_DESK_USER TROUBLE_DESK_USER { get; set; }
    	[DataMember]
        public virtual BY_PASS BY_PASS { get; set; }
    }
}
