//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.Nucleo.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class DEPOT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEPOT()
        {
            this.LINE_DEPOTS = new HashSet<LINE_DEPOTS>();
            this.STOCK_REGISTER = new HashSet<STOCK_REGISTER>();
        }
    
        [DataMember]
        public int ID_DEPOT { get; set; }
        [DataMember]
        public string NAME { get; set; }
        [DataMember]
        public string NOTES { get; set; }
        [DataMember]
        public Nullable<bool> ACTIVE { get; set; }
        [DataMember]
        public Nullable<int> AUXILIAR_STOCK { get; set; }
        [DataMember]
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<LINE_DEPOTS> LINE_DEPOTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<STOCK_REGISTER> STOCK_REGISTER { get; set; }
    }
}
