//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.Nucleo.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class DEVICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEVICE()
        {
            this.USER_SESSIONS = new HashSet<USER_SESSION>();
            this.PRE_GATES = new HashSet<PRE_GATE>();
        }
    
        [DataMember]
        public int DEVICE_ID { get; set; }
        [DataMember]
        public string IP { get; set; }
        [DataMember]
        public string NAME { get; set; }
        [DataMember]
        public bool IS_ACTIVE { get; set; }
        [DataMember]
        public short ZONE_ID { get; set; }
    
    	[DataMember]
        public virtual ZONE ZONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<USER_SESSION> USER_SESSIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<PRE_GATE> PRE_GATES { get; set; }
    }
}
