//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.Nucleo.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class ERROR
    {
        [DataMember]
        public int ERROR_ID { get; set; }
        [DataMember]
        public System.DateTime THROW_ON { get; set; }
        [DataMember]
        public string MESSAGE { get; set; }
        [DataMember]
        public string DETAILS { get; set; }
        [DataMember]
        public int APPLICATION_ID { get; set; }
        [DataMember]
        public int TYPE_ERROR_ID { get; set; }
        [DataMember]
        public string IP_SOURCE { get; set; }
    
    	[DataMember]
        public virtual APPLICATION APPLICATION { get; set; }
    	[DataMember]
        public virtual TYPE_ERROR TYPE_ERROR { get; set; }
    	[DataMember]
        public virtual CLIENT_APP_TRANSACTION_TROUBLE_TICKET CLIENT_APP_TRANSACTION_TROUBLE_TICKET { get; set; }
    }
}
