//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.Nucleo.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class KIOSK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KIOSK()
        {
            this.KIOSK_TRANSACTIONS = new HashSet<KIOSK_TRANSACTION>();
            this.LIFT_UP_BARRIERS = new HashSet<LIFT_UP_BARRIER>();
            this.REPRINTS = new HashSet<REPRINT>();
        }
    
        [DataMember]
        public short KIOSK_ID { get; set; }
        [DataMember]
        public string NAME { get; set; }
        [DataMember]
        public string IP { get; set; }
        [DataMember]
        public bool IS_ACTIVE { get; set; }
        [DataMember]
        public short ZONE_ID { get; set; }
        [DataMember]
        public bool IS_IN { get; set; }
    
    	[DataMember]
        public virtual ZONE ZONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<KIOSK_TRANSACTION> KIOSK_TRANSACTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<LIFT_UP_BARRIER> LIFT_UP_BARRIERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<REPRINT> REPRINTS { get; set; }
    }
}
