//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.Nucleo.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class KIOSK_TRANSACTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KIOSK_TRANSACTION()
        {
            this.PROCESSES = new HashSet<PROCESS>();
            this.SENSOR_KIOSK_TRANSACTIONS = new HashSet<SENSOR_KIOSK_TRANSACTION>();
        }
    
        [DataMember]
        public int TRANSACTION_ID { get; set; }
        [DataMember]
        public bool IS_OK { get; set; }
        [DataMember]
        public System.DateTime START_DATE { get; set; }
        [DataMember]
        public System.DateTime END_DATE { get; set; }
        [DataMember]
        public bool IS_RECYCLED { get; set; }
        [DataMember]
        public short KIOSK_ID { get; set; }
        [DataMember]
        public Nullable<long> PRE_GATE_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<PROCESS> PROCESSES { get; set; }
    	[DataMember]
        public virtual KIOSK KIOSK { get; set; }
    	[DataMember]
        public virtual PRE_GATE PRE_GATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<SENSOR_KIOSK_TRANSACTION> SENSOR_KIOSK_TRANSACTIONS { get; set; }
    }
}
