//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.Nucleo.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class LIFT_UP_BARRIER
    {
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public System.DateTime DATE { get; set; }
        [DataMember]
        public string REASON { get; set; }
        [DataMember]
        public short KIOSK_ID { get; set; }
        [DataMember]
        public int TTU_ID { get; set; }
        [DataMember]
        public Nullable<long> PREGATE_ID { get; set; }
        [DataMember]
        public Nullable<int> MOTIVE_ID { get; set; }
    
    	[DataMember]
        public virtual KIOSK KIOSK { get; set; }
    	[DataMember]
        public virtual TROUBLE_DESK_USER TROUBLE_DESK_USER { get; set; }
    }
}
