//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.Nucleo.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class MESSAGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MESSAGE()
        {
            this.PROCESSES = new HashSet<PROCESS>();
        }
    
        [DataMember]
        public int MESSAGE_ID { get; set; }
        [DataMember]
        public string USER_MESSAGE { get; set; }
        [DataMember]
        public string TROUBLE_DESK_MESSAGE { get; set; }
        [DataMember]
        public string DETAILS { get; set; }
        [DataMember]
        public string TYPE { get; set; }
        [DataMember]
        public byte ATTEMPTS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<PROCESS> PROCESSES { get; set; }
    }
}
