//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.Nucleo.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class MOBILE_TROUBLE_TICKET : TROUBLE_TICKET
    {
        [DataMember]
        public Nullable<long> USER_SESSION_ID { get; set; }
        [DataMember]
        public string MESSAGE { get; set; }
        [DataMember]
        public short ZONE_ID { get; set; }
        [DataMember]
        public Nullable<long> PRE_GATE_ID { get; set; }
    
    	[DataMember]
        public virtual USER_SESSION USER_SESSION { get; set; }
    	[DataMember]
        public virtual TOS_PROCCESS TOS_PROCCESS { get; set; }
    	[DataMember]
        public virtual ZONE ZONE { get; set; }
    	[DataMember]
        public virtual PRE_GATE PRE_GATES { get; set; }
    }
}
