//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.Nucleo.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class PRE_GATE_DETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRE_GATE_DETAIL()
        {
            this.CONTAINERS = new HashSet<CONTAINER>();
        }
    
        [DataMember]
        public long ID { get; set; }
        [DataMember]
        public string TRANSACTION_NUMBER { get; set; }
        [DataMember]
        public bool IS_RECYCLED { get; set; }
        [DataMember]
        public short TRANSACTION_TYPE_ID { get; set; }
        [DataMember]
        public long PRE_GATE_ID { get; set; }
        [DataMember]
        public string STATUS { get; set; }
        [DataMember]
        public string DOCUMENT_ID { get; set; }
        [DataMember]
        public string REFERENCE_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<CONTAINER> CONTAINERS { get; set; }
    	[DataMember]
        public virtual TRANSACTION_TYPE TRANSACTION_TYPE { get; set; }
    	[DataMember]
        public virtual PRE_GATE PRE_GATE { get; set; }
    }
}
