//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.Nucleo.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class PROCESS_TROUBLE_TICKET : TROUBLE_TICKET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROCESS_TROUBLE_TICKET()
        {
            this.REASSIGNMENTS = new HashSet<REASSIGNMENT>();
            this.ACTIONS = new HashSet<ACTION>();
        }
    
        [DataMember]
        public Nullable<long> USER_SESSION_ID { get; set; }
        [DataMember]
        public bool IS_SUSPENDED { get; set; }
    
    	[DataMember]
        public virtual PROCESS PROCESS { get; set; }
    	[DataMember]
        public virtual USER_SESSION USER_SESSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<REASSIGNMENT> REASSIGNMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<ACTION> ACTIONS { get; set; }
    }
}
