//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.Nucleo.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class SENSOR_KIOSK_TRANSACTION
    {
        [DataMember]
        public long ID { get; set; }
        [DataMember]
        public bool VALUE { get; set; }
        [DataMember]
        public short SENSOR_ID { get; set; }
        [DataMember]
        public int TRANSACTION_ID { get; set; }
    
    	[DataMember]
        public virtual SENSOR SENSOR { get; set; }
    	[DataMember]
        public virtual KIOSK_TRANSACTION KIOSK_TRANSACTION { get; set; }
    }
}
