//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.Nucleo.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class SUB_MOTIVE
    {
        [DataMember]
        public int SUB_MOTIVE_ID { get; set; }
        [DataMember]
        public string NAME { get; set; }
        [DataMember]
        public bool ACTIVE { get; set; }
        [DataMember]
        public int MOTIVES_ID { get; set; }
    
    	[DataMember]
        public virtual MOTIVE MOTIVE { get; set; }
    }
}
