//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.Nucleo.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class TOS_PROCCESS
    {
        [DataMember]
        public long ID { get; set; }
        [DataMember]
        public string STEP { get; set; }
        [DataMember]
        public System.DateTime STEP_DATE { get; set; }
        [DataMember]
        public bool IS_OK { get; set; }
        [DataMember]
        public string RESPONSE { get; set; }
        [DataMember]
        public bool IS_RECYCLED { get; set; }
        [DataMember]
        public long PRE_GATE_ID { get; set; }
    
    	[DataMember]
        public virtual PRE_GATE PRE_GATE { get; set; }
    	[DataMember]
        public virtual MOBILE_TROUBLE_TICKET MOBILE_TROUBLE_TICKET { get; set; }
    }
}
