//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.Nucleo.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class TROUBLE_DESK_USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TROUBLE_DESK_USER()
        {
            this.USER_SESSIONS = new HashSet<USER_SESSION>();
            this.LIFT_UP_BARRIERS = new HashSet<LIFT_UP_BARRIER>();
            this.REPRINTS = new HashSet<REPRINT>();
            this.BY_PASS_AUDITS = new HashSet<BY_PASS_AUDIT>();
        }
    
        [DataMember]
        public int TTU_ID { get; set; }
        [DataMember]
        public string FIRST_NAME { get; set; }
        [DataMember]
        public string LAST_NAME { get; set; }
        [DataMember]
        public string USER_NAME { get; set; }
        [DataMember]
        public bool IS_ACTIVE { get; set; }
        [DataMember]
        public string EMAIL { get; set; }
        [DataMember]
        public bool IS_TD { get; set; }
        [DataMember]
        public bool IS_SUPERVISOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<USER_SESSION> USER_SESSIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<LIFT_UP_BARRIER> LIFT_UP_BARRIERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<REPRINT> REPRINTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<BY_PASS_AUDIT> BY_PASS_AUDITS { get; set; }
    }
}
