//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.Nucleo.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class TROUBLE_TICKET
    {
        [DataMember]
        public long TT_ID { get; set; }
        [DataMember]
        public System.DateTime CREATION_DATE { get; set; }
        [DataMember]
        public Nullable<System.DateTime> ACCEPTANCE_DATE { get; set; }
        [DataMember]
        public Nullable<System.DateTime> FINISH_DATE { get; set; }
        [DataMember]
        public string NOTES { get; set; }
        [DataMember]
        public bool IS_CANCEL { get; set; }
        [DataMember]
        public bool IS_RECYCLED { get; set; }
        [DataMember]
        public Nullable<System.DateTime> ASSIGNMENT_DATE { get; set; }
        [DataMember]
        public string CANCEL_USER { get; set; }
        [DataMember]
        public Nullable<System.DateTime> CANCEL_DATE { get; set; }
        [DataMember]
        public Nullable<int> SUBMOTIVE_ID { get; set; }
        [DataMember]
        public Nullable<int> MOTIVE_ID { get; set; }
    }
}
