//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.Nucleo.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class USER_SESSION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER_SESSION()
        {
            this.BREAKS = new HashSet<BREAK>();
            this.REASSIGNMENTS = new HashSet<REASSIGNMENT>();
            this.AUTO_TROUBLE_TICKETS = new HashSet<AUTO_TROUBLE_TICKET>();
            this.PROCESS_TROUBLE_TICKETS = new HashSet<PROCESS_TROUBLE_TICKET>();
            this.MOBILE_TROUBLE_TICKETS = new HashSet<MOBILE_TROUBLE_TICKET>();
            this.CLIENT_APP_TRANSACTION_TROUBLE_TICKETS = new HashSet<CLIENT_APP_TRANSACTION_TROUBLE_TICKET>();
        }
    
        [DataMember]
        public long ID { get; set; }
        [DataMember]
        public System.DateTime START_SESSION__DATE { get; set; }
        [DataMember]
        public Nullable<System.DateTime> FINISH_SESSION_DATE { get; set; }
        [DataMember]
        public int DEVICE_ID { get; set; }
        [DataMember]
        public int TTU_ID { get; set; }
        [DataMember]
        public bool IS_RECYCLED { get; set; }
    
    	[DataMember]
        public virtual DEVICE DEVICE { get; set; }
    	[DataMember]
        public virtual TROUBLE_DESK_USER TROUBLE_DESK_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<BREAK> BREAKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<REASSIGNMENT> REASSIGNMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<AUTO_TROUBLE_TICKET> AUTO_TROUBLE_TICKETS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<PROCESS_TROUBLE_TICKET> PROCESS_TROUBLE_TICKETS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<MOBILE_TROUBLE_TICKET> MOBILE_TROUBLE_TICKETS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<CLIENT_APP_TRANSACTION_TROUBLE_TICKET> CLIENT_APP_TRANSACTION_TROUBLE_TICKETS { get; set; }
    }
}
