//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaDominio.Nucleo.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class ZONE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZONE()
        {
            this.KIOSKS = new HashSet<KIOSK>();
            this.DEVICES = new HashSet<DEVICE>();
            this.TRANSACTION_TYPES = new HashSet<TRANSACTION_TYPE>();
            this.CLIENT_APP_TRANSACTION_TROUBLE_TICKETS = new HashSet<CLIENT_APP_TRANSACTION_TROUBLE_TICKET>();
            this.MOBILE_TROUBLE_TICKETS = new HashSet<MOBILE_TROUBLE_TICKET>();
        }
    
        [DataMember]
        public short ZONE_ID { get; set; }
        [DataMember]
        public string NAME { get; set; }
        [DataMember]
        public bool IS_ACTIVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<KIOSK> KIOSKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<DEVICE> DEVICES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<TRANSACTION_TYPE> TRANSACTION_TYPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<CLIENT_APP_TRANSACTION_TROUBLE_TICKET> CLIENT_APP_TRANSACTION_TROUBLE_TICKETS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<MOBILE_TROUBLE_TICKET> MOBILE_TROUBLE_TICKETS { get; set; }
    }
}
