//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaPresentacion.UI.ImpresoraZebra {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TablaAdvertenciasImpresoraZebra {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TablaAdvertenciasImpresoraZebra() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RECEPTIO.CapaPresentacion.UI.ImpresoraZebra.TablaAdvertenciasImpresoraZebra", typeof(TablaAdvertenciasImpresoraZebra).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Necesidad de calibrar los medios..
        /// </summary>
        internal static string Nibble1_1 {
            get {
                return ResourceManager.GetString("Nibble1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar cabeza de impresión..
        /// </summary>
        internal static string Nibble1_2 {
            get {
                return ResourceManager.GetString("Nibble1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reemplace el cabezal..
        /// </summary>
        internal static string Nibble1_4 {
            get {
                return ResourceManager.GetString("Nibble1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sensor de papel cerca del final..
        /// </summary>
        internal static string Nibble1_8 {
            get {
                return ResourceManager.GetString("Nibble1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sensor 1 (papel antes de la cabeza)..
        /// </summary>
        internal static string Nibble2_1 {
            get {
                return ResourceManager.GetString("Nibble2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sensor 2 (marca negra)..
        /// </summary>
        internal static string Nibble2_2 {
            get {
                return ResourceManager.GetString("Nibble2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sensor 3 (Papel después de la cabeza)..
        /// </summary>
        internal static string Nibble2_4 {
            get {
                return ResourceManager.GetString("Nibble2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sensor 4 (lazo listo)..
        /// </summary>
        internal static string Nibble2_8 {
            get {
                return ResourceManager.GetString("Nibble2_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sensor 5 (presentador)..
        /// </summary>
        internal static string Nibble3_1 {
            get {
                return ResourceManager.GetString("Nibble3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sensor 6 (retraer listo)..
        /// </summary>
        internal static string Nibble3_2 {
            get {
                return ResourceManager.GetString("Nibble3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sensor 7 (en retracción)..
        /// </summary>
        internal static string Nibble3_4 {
            get {
                return ResourceManager.GetString("Nibble3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sensor 8 (en el contenedor)..
        /// </summary>
        internal static string Nibble3_8 {
            get {
                return ResourceManager.GetString("Nibble3_8", resourceCulture);
            }
        }
    }
}
