//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RECEPTIO.CapaPresentacion.UI.ImpresoraZebra {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TablaErroresImpresoraZebra {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TablaErroresImpresoraZebra() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RECEPTIO.CapaPresentacion.UI.ImpresoraZebra.TablaErroresImpresoraZebra", typeof(TablaErroresImpresoraZebra).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay papel..
        /// </summary>
        internal static string Nibble1_1 {
            get {
                return ResourceManager.GetString("Nibble1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Papel afuera..
        /// </summary>
        internal static string Nibble1_2 {
            get {
                return ResourceManager.GetString("Nibble1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cabezal abierto..
        /// </summary>
        internal static string Nibble1_4 {
            get {
                return ResourceManager.GetString("Nibble1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falla de cortador..
        /// </summary>
        internal static string Nibble1_8 {
            get {
                return ResourceManager.GetString("Nibble1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cabezal de impresión sobre temperatura..
        /// </summary>
        internal static string Nibble2_1 {
            get {
                return ResourceManager.GetString("Nibble2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sobrecalentamiento del motor..
        /// </summary>
        internal static string Nibble2_2 {
            get {
                return ResourceManager.GetString("Nibble2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elemento del cabezal de impresión defectuoso..
        /// </summary>
        internal static string Nibble2_4 {
            get {
                return ResourceManager.GetString("Nibble2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de detección del cabezal de impresión..
        /// </summary>
        internal static string Nibble2_8 {
            get {
                return ResourceManager.GetString("Nibble2_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración de firmware inválida..
        /// </summary>
        internal static string Nibble3_1 {
            get {
                return ResourceManager.GetString("Nibble3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Termistor del cabezal de impresión abierto..
        /// </summary>
        internal static string Nibble3_2 {
            get {
                return ResourceManager.GetString("Nibble3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atasco de papel durante la retractación..
        /// </summary>
        internal static string Nibble4_1 {
            get {
                return ResourceManager.GetString("Nibble4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presentador no está ejecutándose..
        /// </summary>
        internal static string Nibble4_2 {
            get {
                return ResourceManager.GetString("Nibble4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de alimentación de papel..
        /// </summary>
        internal static string Nibble4_4 {
            get {
                return ResourceManager.GetString("Nibble4_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Despejar la ruta del papel fallida..
        /// </summary>
        internal static string Nibble4_8 {
            get {
                return ResourceManager.GetString("Nibble4_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pausado..
        /// </summary>
        internal static string Nibble5_1 {
            get {
                return ResourceManager.GetString("Nibble5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Función de retracción agotada..
        /// </summary>
        internal static string Nibble5_2 {
            get {
                return ResourceManager.GetString("Nibble5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de calibración de marca negra..
        /// </summary>
        internal static string Nibble5_4 {
            get {
                return ResourceManager.GetString("Nibble5_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca negra no encontrada..
        /// </summary>
        internal static string Nibble5_8 {
            get {
                return ResourceManager.GetString("Nibble5_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La impresora no está conectada..
        /// </summary>
        internal static string NoConectada {
            get {
                return ResourceManager.GetString("NoConectada", resourceCulture);
            }
        }
    }
}
