//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transaction.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Transaction.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 23.
        /// </summary>
        internal static string IdMensajeGeneralEnvioProblema {
            get {
                return ResourceManager.GetString("IdMensajeGeneralEnvioProblema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Levantando Barrera..
        /// </summary>
        internal static string MensajeBarrera {
            get {
                return ResourceManager.GetString("MensajeBarrera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingrese su huella..
        /// </summary>
        internal static string MensajeBiometrico {
            get {
                return ResourceManager.GetString("MensajeBiometrico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimiendo Ticket..
        /// </summary>
        internal static string MensajeImpresion {
            get {
                return ResourceManager.GetString("MensajeImpresion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Digite el número de cédula del conductor y luego presione el botón verde OK..
        /// </summary>
        internal static string MensajeInicioEntrada {
            get {
                return ResourceManager.GetString("MensajeInicioEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aproxime el ticket al lector de código de barra ubicada en la parte inferior izquierda. O digite el código ubicado abajo del código de barras del ticket y luego presione el botón verde OK..
        /// </summary>
        internal static string MensajeInicioSalida {
            get {
                return ResourceManager.GetString("MensajeInicioSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizando procesos..
        /// </summary>
        internal static string MensajeProcesosN4 {
            get {
                return ResourceManager.GetString("MensajeProcesosN4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escaneo de Tag RFID..
        /// </summary>
        internal static string MensajeRfid {
            get {
                return ResourceManager.GetString("MensajeRfid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesando......
        /// </summary>
        internal static string Procesando {
            get {
                return ResourceManager.GetString("Procesando", resourceCulture);
            }
        }
    }
}
